/**
 * Human-readable names, aliases, and descriptions for financial symbols.
 *
 * AUTO-GENERATED from data/company-profiles.json
 * Do NOT edit manually — run: npx tsx scripts/sync-asset-names.ts
 *
 * 769 symbols (watchlist + 727 stocks + watchlist assets)
 */

/** Symbol → display name */
export const ASSET_NAMES: Record<string, string> = {
  "^DJI": "Dow Jones",
  "^FCHI": "CAC 40",
  "^FTSE": "FTSE 100",
  "^FVX": "US 5Y",
  "^GDAXI": "DAX",
  "^GSPC": "S&P 500",
  "^HSI": "Hang Seng",
  "^IRX": "US 3M",
  "^IXIC": "Nasdaq Composite",
  "^KS11": "KOSPI",
  "^N225": "Nikkei 225",
  "^STOXX": "Euro Stoxx 600",
  "^TNX": "US 10Y",
  "^TYX": "US 30Y",
  "^VIX": "VIX",
  "000001.SS": "Shanghai Composite",
  "0001.HK": "CK Hutchison",
  "0002.HK": "CLP Holdings",
  "0003.HK": "HK & China Gas",
  "0005.HK": "HSBC Holdings",
  "0006.HK": "Power Assets",
  "0011.HK": "Hang Seng Bank",
  "0012.HK": "Henderson Land",
  "0016.HK": "Sun Hung Kai Properties",
  "0017.HK": "New World Development",
  "0388.HK": "Hong Kong Exchanges",
  "0669.HK": "Techtronic Industries",
  "0688.HK": "China Overseas Land",
  "0700.HK": "Tencent Holdings",
  "0762.HK": "China Unicom",
  "0883.HK": "CNOOC",
  "0939.HK": "China Construction Bank",
  "0941.HK": "China Mobile",
  "0960.HK": "Longfor Properties",
  "1038.HK": "CK Infrastructure",
  "1093.HK": "CSPC Pharmaceutical",
  "1177.HK": "Sino Biopharmaceutical",
  "1299.HK": "AIA Group",
  "1398.HK": "ICBC",
  "1COV.DE": "Covestro",
  "2269.HK": "WuXi Biologics",
  "2318.HK": "Ping An Insurance",
  "2382.HK": "Sunny Optical",
  "3382.T": "Seven & I Holdings",
  "3690.HK": "Meituan",
  "399001.SZ": "Shenzhen Component",
  "4063.T": "Shin-Etsu Chemical",
  "4502.T": "Takeda Pharmaceutical",
  "4507.T": "Shionogi",
  "4519.T": "Chugai Pharmaceutical",
  "4543.T": "Terumo",
  "4568.T": "Daiichi Sankyo",
  "4661.T": "Oriental Land",
  "4704.T": "Trend Micro",
  "4911.T": "Shiseido",
  "5108.T": "Bridgestone",
  "6098.T": "Recruit Holdings",
  "6273.T": "SMC Corporation",
  "6367.T": "Daikin Industries",
  "6501.T": "Hitachi",
  "6752.T": "Panasonic",
  "6758.T": "Sony Group",
  "6861.T": "Keyence",
  "6902.T": "Denso",
  "6954.T": "Fanuc",
  "7011.T": "Mitsubishi Heavy Industries",
  "7203.T": "Toyota Motor",
  "7267.T": "Honda Motor",
  "7733.T": "Olympus",
  "7741.T": "HOYA",
  "7832.T": "Bandai Namco",
  "7974.T": "Nintendo",
  "8031.T": "Mitsui & Co.",
  "8035.T": "Tokyo Electron",
  "8053.T": "Sumitomo Corporation",
  "8058.T": "Mitsubishi Corporation",
  "8306.T": "Mitsubishi UFJ Financial",
  "8316.T": "Sumitomo Mitsui Financial",
  "8801.T": "Mitsui Fudosan",
  "9020.T": "East Japan Railway",
  "9022.T": "Central Japan Railway",
  "9432.T": "NTT",
  "9433.T": "KDDI",
  "9613.T": "NTT Data",
  "9618.HK": "JD.com",
  "9984.T": "SoftBank Group",
  "9988.HK": "Alibaba Group",
  "9999.HK": "NetEase",
  "A": "Agilent Technologies Inc",
  "AA": "Alcoa Corp",
  "AAL": "American Airlines Group Inc",
  "AAL.L": "Anglo American",
  "AAPL": "Apple Inc",
  "ABBV": "AbbVie Inc",
  "ABNB": "Airbnb Inc",
  "ABT": "Abbott Laboratories",
  "ACA.PA": "Crédit Agricole",
  "ACGL": "Arch Capital Group",
  "ACN": "Accenture PLC",
  "ADBE": "Adobe Inc.",
  "ADI": "Analog Devices Inc",
  "ADM": "Archer Daniels Midland",
  "ADP": "Automatic Data Processing Inc",
  "ADS.DE": "Adidas",
  "ADSK": "Autodesk",
  "AEE": "Ameren",
  "AEP": "American Electric Power",
  "AES": "AES Corporation",
  "AFL": "Aflac Inc",
  "AI.PA": "Air Liquide",
  "AIG": "American International Group Inc",
  "AIR.DE": "Airbus",
  "AIR.PA": "Airbus",
  "AIZ": "Assurant",
  "AJG": "Arthur J. Gallagher & Co.",
  "AKAM": "Akamai Technologies",
  "ALB": "Albemarle Corp",
  "ALGN": "Align Technology",
  "ALK": "Alaska Air Group Inc",
  "ALL": "Allstate Corp",
  "ALLE": "Allegion",
  "ALV.DE": "Allianz",
  "AMAT": "Applied Materials Inc",
  "AMCR": "Amcor",
  "AMD": "Advanced Micro Devices Inc",
  "AME": "AMETEK Inc",
  "AMGN": "Amgen Inc",
  "AMP": "Ameriprise Financial",
  "AMT": "American Tower Corp",
  "AMZN": "Amazon.com Inc",
  "ANET": "Arista Networks",
  "ANTO.L": "Antofagasta",
  "AON": "Aon plc",
  "AOS": "A. O. Smith",
  "APA": "APA Corporation",
  "APD": "Air Products and Chemicals Inc",
  "APH": "Amphenol",
  "APO": "Apollo Global Management",
  "APP": "Applovin Corp",
  "APTV": "Aptiv",
  "ARE": "Alexandria Real Estate Equities",
  "ARES": "Ares Management",
  "ARM": "Arm Holdings PLC",
  "ATO": "Atmos Energy",
  "AUDUSD=X": "AUD/USD",
  "AVB": "AvalonBay Communities",
  "AVGO": "Broadcom Inc",
  "AVY": "Avery Dennison Corp",
  "AWK": "American Water Works",
  "AXA.PA": "AXA",
  "AXON": "Axon Enterprise Inc",
  "AXP": "American Express Co",
  "AZN.L": "AstraZeneca",
  "AZO": "AutoZone",
  "BA": "Boeing Co",
  "BAC": "Bank of America Corp",
  "BALL": "Ball Corporation",
  "BAS.DE": "BASF",
  "BAT.L": "British American Tobacco",
  "BATS.L": "BAE Systems",
  "BAX": "Baxter International",
  "BAYN.DE": "Bayer",
  "BBY": "Best Buy",
  "BDX": "Becton Dickinson and Co",
  "BEI.DE": "Beiersdorf",
  "BEN": "Franklin Resources",
  "BF.B": "Brown���Forman",
  "BG": "Bunge Global",
  "BIIB": "Biogen",
  "BIO": "Bio Rad Laboratories Inc",
  "BK": "BNY Mellon",
  "BKNG": "Booking Holdings Inc",
  "BKR": "Baker Hughes Co",
  "BLDR": "Builders FirstSource",
  "BLK": "BlackRock Inc",
  "BMW.DE": "BMW",
  "BMY": "Bristol Myers Squibb",
  "BN.PA": "Danone",
  "BNP.PA": "BNP Paribas",
  "BNR.DE": "Brenntag",
  "BP.L": "BP",
  "BR": "Broadridge Financial Solutions",
  "BRK-B": "Berkshire Hathaway Inc",
  "BRK.B": "Berkshire Hathaway",
  "BRO": "Brown & Brown",
  "BSX": "Boston Scientific Corp",
  "BT-A.L": "BT Group",
  "BTC-USD": "Bitcoin",
  "BX": "Blackstone Inc.",
  "BXP": "\"BXP",
  "BZ=F": "Brent",
  "C": "Citigroup Inc",
  "CA.PA": "Carrefour",
  "CAG": "Conagra Brands",
  "CAH": "Cardinal Health",
  "CAP.PA": "Capgemini",
  "CARR": "Carrier Global",
  "CAT": "Caterpillar Inc",
  "CB": "Chubb Ltd",
  "CBK.DE": "Commerzbank",
  "CBOE": "Cboe Global Markets",
  "CBRE": "CBRE Group",
  "CCI": "Crown Castle",
  "CCL": "Carnival Corp",
  "CDNS": "Cadence Design Systems",
  "CDW": "CDW Corporation",
  "CE": "Celanese Corp",
  "CEG": "Constellation Energy",
  "CF": "CF Industries Holdings Inc",
  "CFG": "Citizens Financial Group",
  "CHD": "Church & Dwight",
  "CHRW": "C.H. Robinson",
  "CHTR": "Charter Communications Inc",
  "CI": "Cigna Group",
  "CIEN": "Ciena",
  "CINF": "Cincinnati Financial",
  "CL": "Colgate-Palmolive",
  "CL=F": "Pétrole WTI",
  "CLF": "Cleveland-Cliffs Inc",
  "CLX": "Clorox",
  "CMCSA": "Comcast Corp",
  "CME": "CME Group Inc",
  "CMG": "Chipotle Mexican Grill Inc",
  "CMI": "Cummins",
  "CMS": "CMS Energy",
  "CNA.L": "Centrica",
  "CNC": "Centene Corp",
  "CNP": "CenterPoint Energy",
  "COF": "Capital One Financial Corp",
  "COIN": "Coinbase Global Inc",
  "CON.DE": "Continental",
  "COO": "Cooper Companies (The)",
  "COP": "ConocoPhillips",
  "COR": "Cencora",
  "COST": "Costco Wholesale Corp",
  "CPAY": "Corpay",
  "CPB": "Campbell's Company (The)",
  "CPG.L": "Compass Group",
  "CPRT": "Copart",
  "CPT": "Camden Property Trust",
  "CRH": "CRH plc",
  "CRL": "Charles River Laboratories",
  "CRM": "Salesforce Inc",
  "CRWD": "CrowdStrike Holdings Inc",
  "CSCO": "Cisco Systems Inc",
  "CSGP": "CoStar Group",
  "CSX": "CSX Corporation",
  "CTAS": "Cintas Corp",
  "CTRA": "Coterra",
  "CTSH": "Cognizant",
  "CTVA": "Corteva",
  "CVNA": "Carvana",
  "CVS": "CVS Health",
  "CVX": "Chevron Corp",
  "D": "Dominion Energy Inc",
  "DAL": "Delta Air Lines Inc",
  "DASH": "DoorDash Inc",
  "DB1.DE": "Deutsche Börse",
  "DBK.DE": "Deutsche Bank",
  "DD": "Dupont De Nemours Inc",
  "DDOG": "Datadog Inc",
  "DE": "Deere & Co",
  "DECK": "Deckers Brands",
  "DELL": "Dell Technologies Inc",
  "DG": "Dollar General",
  "DG.PA": "Vinci",
  "DGE.L": "Diageo",
  "DGX": "Quest Diagnostics",
  "DHER.DE": "Delivery Hero",
  "DHI": "D.R. Horton Inc",
  "DHL.DE": "DHL Group",
  "DHR": "Danaher Corp",
  "DIS": "Walt Disney Co",
  "DLR": "Digital Realty",
  "DLTR": "Dollar Tree",
  "DOC": "Healthpeak Properties",
  "DOV": "Dover Corporation",
  "DOW": "Dow Inc",
  "DPZ": "Domino's",
  "DRI": "Darden Restaurants",
  "DSY.PA": "Dassault Systèmes",
  "DTE": "DTE Energy",
  "DTE.DE": "Deutsche Telekom",
  "DUK": "Duke Energy Corp",
  "DVA": "DaVita",
  "DVN": "Devon Energy Corp",
  "DX-Y.NYB": "Dollar Index",
  "DXCM": "Dexcom",
  "EA": "Electronic Arts",
  "EBAY": "eBay Inc.",
  "ECL": "Ecolab Inc",
  "ED": "Consolidated Edison",
  "EFX": "Equifax",
  "EG": "Everest Group",
  "EIX": "Edison International",
  "EL": "Estée Lauder Companies (The)",
  "EL.PA": "EssilorLuxottica",
  "ELV": "Elevance Health Inc",
  "EME": "Emcor",
  "EMR": "Emerson Electric Co",
  "EN.PA": "Bouygues",
  "ENGI.PA": "Engie",
  "ENR.DE": "Siemens Energy",
  "EOAN.DE": "E.ON",
  "EOG": "EOG Resources Inc",
  "EPAM": "EPAM Systems",
  "EQIX": "Equinix Inc",
  "EQR": "Equity Residential",
  "EQT": "EQT Corporation",
  "ERF.PA": "Eurofins Scientific",
  "ERIE": "Erie Indemnity",
  "ES": "Eversource Energy",
  "ESS": "Essex Property Trust",
  "ETH-USD": "Ethereum",
  "ETN": "Eaton Corporation PLC",
  "ETR": "Entergy",
  "EURGBP=X": "EUR/GBP",
  "EURJPY=X": "EUR/JPY",
  "EURUSD=X": "EUR/USD",
  "EVRG": "Evergy",
  "EW": "Edwards Lifesciences",
  "EXC": "Exelon Corp",
  "EXE": "Expand Energy",
  "EXPD": "Expeditors International",
  "EXPE": "Expedia Group",
  "EXPN.L": "Experian",
  "EXR": "Extra Space Storage",
  "EZJ.L": "easyJet",
  "F": "Ford Motor Co",
  "FANG": "Diamondback Energy Inc",
  "FAST": "Fastenal Co",
  "FCX": "Freeport-McMoRan Inc",
  "FDS": "Factset Research Systems Inc",
  "FDX": "FedEx Corp",
  "FE": "FirstEnergy",
  "FERG.L": "Ferguson",
  "FFIV": "\"F5",
  "FICO": "Fair Isaac",
  "FIS": "Fidelity National Information Services",
  "FISV": "Fiserv",
  "FITB": "Fifth Third Bancorp",
  "FIX": "Comfort Systems USA",
  "FLTR.L": "Flutter Entertainment",
  "FOX": "Fox Corporation (Class B)",
  "FOXA": "Fox Corporation (Class A)",
  "FRE.DE": "Fresenius",
  "FRT": "Federal Realty Investment Trust",
  "FSLR": "First Solar",
  "FTNT": "Fortinet",
  "FTV": "Fortive Corp",
  "GBPJPY=X": "GBP/JPY",
  "GBPUSD=X": "GBP/USD",
  "GC=F": "Or",
  "GD": "General Dynamics Corp",
  "GDDY": "GoDaddy",
  "GE": "General Electric Co",
  "GEHC": "GE HealthCare",
  "GEN": "Gen Digital",
  "GEV": "GE Vernova",
  "GILD": "Gilead Sciences Inc",
  "GIS": "General Mills",
  "GL": "Globe Life",
  "GLE.PA": "Société Générale",
  "GLEN.L": "Glencore",
  "GLW": "Corning Inc.",
  "GM": "General Motors Co",
  "GNRC": "Generac",
  "GOOG": "Alphabet Inc",
  "GOOGL": "Alphabet Inc",
  "GPC": "Genuine Parts Company",
  "GPN": "Global Payments",
  "GRMN": "Garmin",
  "GS": "Goldman Sachs Group Inc",
  "GSK.L": "GSK",
  "GWW": "WW Grainger Inc",
  "H": "Hyatt Hotels Corp",
  "HAL": "Halliburton Co",
  "HAS": "Hasbro",
  "HBAN": "Huntington Bancshares",
  "HCA": "HCA Healthcare Inc",
  "HD": "Home Depot Inc",
  "HEI.DE": "HeidelbergMaterials",
  "HFG.DE": "HelloFresh",
  "HG=F": "Cuivre",
  "HIG": "Hartford (The)",
  "HII": "Huntington Ingalls Industries Inc",
  "HLN.L": "Haleon",
  "HLT": "Hilton Worldwide Holdings Inc",
  "HNR1.DE": "Hannover Re",
  "HO.PA": "Thales",
  "HOLX": "Hologic",
  "HON": "Honeywell International Inc",
  "HOOD": "Robinhood Markets",
  "HPE": "Hewlett Packard Enterprise Co",
  "HPQ": "HP Inc",
  "HRL": "Hormel Foods",
  "HSBA.L": "HSBC",
  "HSIC": "Henry Schein",
  "HST": "Host Hotels & Resorts",
  "HSY": "Hershey Company (The)",
  "HUBB": "Hubbell Incorporated",
  "HUM": "Humana Inc",
  "HWM": "Howmet Aerospace",
  "IAG.L": "IAG",
  "IBKR": "Interactive Brokers",
  "IBM": "International Business Machines Corp",
  "ICE": "Intercontinental Exchange Inc",
  "IDXX": "IDEXX Laboratories Inc",
  "IEX": "IDEX Corporation",
  "IFF": "International Flavors & Fragrances Inc",
  "IFX.DE": "Infineon Technologies",
  "IHG.L": "InterContinental Hotels",
  "III.L": "3i Group",
  "ILMN": "Illumina Inc",
  "IMB.L": "Imperial Brands",
  "INCY": "Incyte",
  "INTC": "Intel Corp",
  "INTU": "Intuit Inc",
  "INVH": "Invitation Homes",
  "IP": "International Paper Co",
  "IQV": "IQVIA Holdings Inc",
  "IR": "Ingersoll Rand Inc",
  "IRM": "Iron Mountain",
  "ISRG": "Intuitive Surgical Inc",
  "IT": "Gartner",
  "ITW": "Illinois Tool Works Inc",
  "IVZ": "Invesco",
  "J": "Jacobs Solutions",
  "JBHT": "J.B. Hunt",
  "JBL": "Jabil",
  "JCI": "Johnson Controls",
  "JKHY": "Jack Henry & Associates",
  "JNJ": "Johnson & Johnson",
  "JPM": "JPMorgan Chase & Co",
  "KDP": "Keurig Dr Pepper",
  "KER.PA": "Kering",
  "KEY": "KeyCorp",
  "KEYS": "Keysight Technologies Inc",
  "KHC": "Kraft Heinz",
  "KIM": "Kimco Realty",
  "KKR": "KKR & Co Inc",
  "KLAC": "KLA Corp",
  "KMB": "Kimberly-Clark",
  "KMI": "Kinder Morgan",
  "KO": "Coca-Cola Co",
  "KR": "Kroger",
  "KVUE": "Kenvue",
  "L": "Loews Corporation",
  "LDOS": "Leidos Holdings Inc",
  "LEN": "Lennar Corp",
  "LGEN.L": "Legal & General",
  "LH": "Labcorp",
  "LHX": "L3Harris Technologies Inc",
  "LII": "Lennox International",
  "LIN": "Linde PLC",
  "LLOY.L": "Lloyds Banking Group",
  "LLY": "Eli Lilly and Co",
  "LMT": "Lockheed Martin Corp",
  "LNT": "Alliant Energy",
  "LOW": "Lowe's Companies Inc",
  "LR.PA": "Legrand",
  "LRCX": "Lam Research Corp",
  "LULU": "Lululemon Athletica",
  "LUV": "Southwest Airlines Co",
  "LVS": "Las Vegas Sands Corp",
  "LW": "Lamb Weston",
  "LYB": "LyondellBasell Industries NV",
  "LYFT": "Lyft Inc",
  "LYV": "Live Nation Entertainment",
  "MA": "Mastercard Inc",
  "MAA": "Mid-America Apartment Communities",
  "MAR": "Marriott International Inc",
  "MAS": "Masco",
  "MBG.DE": "Mercedes-Benz",
  "MC.PA": "LVMH",
  "MCD": "McDonald's Corp",
  "MCHP": "Microchip Technology",
  "MCK": "McKesson Corporation",
  "MCO": "Moody's Corp",
  "MDLZ": "Mondelez International",
  "MDT": "Medtronic PLC",
  "MET": "MetLife Inc",
  "META": "Meta Platforms Inc",
  "MGM": "MGM Resorts International",
  "MKC": "McCormick & Company",
  "ML.PA": "Michelin",
  "MLM": "Martin Marietta Materials",
  "MMC": "Marsh & McLennan",
  "MMM": "3M Co",
  "MNDI.L": "Mondi",
  "MNG.L": "M&G",
  "MNST": "Monster Beverage",
  "MO": "Altria Group Inc",
  "MOH": "Molina Healthcare",
  "MOS": "Mosaic Co",
  "MPC": "Marathon Petroleum Corp",
  "MPWR": "Monolithic Power Systems",
  "MRK": "Merck & Co Inc",
  "MRK.DE": "Merck KGaA",
  "MRNA": "Moderna",
  "MRSH": "Marsh McLennan",
  "MS": "Morgan Stanley",
  "MSCI": "MSCI Inc",
  "MSFT": "Microsoft Corp",
  "MSI": "Motorola Solutions",
  "MT.AS": "ArcelorMittal",
  "MTB": "M&T Bank",
  "MTCH": "Match Group",
  "MTD": "Mettler-Toledo International Inc",
  "MTX.DE": "MTU Aero Engines",
  "MU": "Micron Technology Inc",
  "MUV2.DE": "Munich Re",
  "NCLH": "Norwegian Cruise Line Holdings Ltd",
  "NDAQ": "\"Nasdaq",
  "NDSN": "Nordson Corporation",
  "NEE": "Nextera Energy Inc",
  "NEM": "Newmont Corporation",
  "NET": "Cloudflare Inc",
  "NFLX": "Netflix Inc",
  "NG.L": "National Grid",
  "NG=F": "Gaz naturel",
  "NI": "NiSource",
  "NKE": "Nike Inc",
  "NOC": "Northrop Grumman Corp",
  "NOW": "ServiceNow Inc",
  "NRG": "NRG Energy",
  "NSC": "Norfolk Southern Corp",
  "NTAP": "NetApp",
  "NTRS": "Northern Trust",
  "NUE": "Nucor Corp",
  "NVDA": "NVIDIA Corp",
  "NVR": "NVR Inc",
  "NWG.L": "NatWest Group",
  "NWS": "News Corp (Class B)",
  "NWSA": "News Corp (Class A)",
  "NXPI": "NXP Semiconductors",
  "NZDUSD=X": "NZD/USD",
  "O": "Realty Income",
  "ODFL": "Old Dominion",
  "OKE": "ONEOK Inc",
  "OKTA": "Okta Inc",
  "OMC": "Omnicom Group",
  "ON": "ON Semiconductor",
  "OR.PA": "L'Oréal",
  "ORA.PA": "Orange",
  "ORCL": "Oracle Corp",
  "ORLY": "O’Reilly Automotive",
  "OTIS": "Otis Worldwide",
  "OXY": "Occidental Petroleum",
  "P911.DE": "Porsche AG",
  "PAH3.DE": "Porsche SE",
  "PANW": "Palo Alto Networks Inc",
  "PAYC": "Paycom",
  "PAYX": "Paychex",
  "PCAR": "Paccar",
  "PCG": "PG&E Corporation",
  "PEG": "Public Service Enterprise Group",
  "PEP": "PepsiCo Inc",
  "PFE": "Pfizer",
  "PFG": "Principal Financial Group",
  "PG": "Procter & Gamble Co",
  "PGR": "Progressive Corp",
  "PH": "Parker-Hannifin Corp",
  "PHM": "Pultegroup Inc",
  "PKG": "Packaging Corp of America",
  "PL=F": "Platine",
  "PLD": "Prologis Inc",
  "PLTR": "Palantir Technologies Inc",
  "PM": "Philip Morris International Inc",
  "PNC": "PNC Financial Services Group Inc",
  "PNR": "Pentair",
  "PNW": "Pinnacle West Capital",
  "PODD": "Insulet Corporation",
  "POOL": "Pool Corporation",
  "PPG": "PPG Industries",
  "PPL": "PPL Corporation",
  "PRU": "Prudential Financial Inc",
  "PRU.L": "Prudential",
  "PSA": "Public Storage",
  "PSKY": "Paramount Skydance Corporation",
  "PSON.L": "Pearson",
  "PSX": "Phillips 66",
  "PTC": "PTC Inc.",
  "PUB.PA": "Publicis Groupe",
  "PWR": "Quanta Services",
  "PXD": "Pioneer Natural Resources",
  "PYPL": "PayPal Holdings Inc",
  "Q": "Qnity Electronics",
  "QCOM": "Qualcomm Inc",
  "QGEN.DE": "Qiagen",
  "RCL": "Royal Caribbean Cruises Ltd",
  "REG": "Regency Centers",
  "REGN": "Regeneron Pharmaceuticals Inc",
  "REL.L": "RELX",
  "RF": "Regions Financial Corporation",
  "RHM.DE": "Rheinmetall",
  "RI.PA": "Pernod Ricard",
  "RIO.L": "Rio Tinto",
  "RJF": "Raymond James Financial",
  "RKT.L": "Reckitt",
  "RL": "Ralph Lauren Corporation",
  "RMD": "ResMed",
  "RMS.PA": "Hermès",
  "RNO.PA": "Renault",
  "ROK": "Rockwell Automation Inc",
  "ROL": "\"Rollins",
  "ROP": "Roper Technologies",
  "ROST": "Ross Stores",
  "RR.L": "Rolls-Royce",
  "RSG": "Republic Services Inc",
  "RTX": "RTX Corp",
  "RVTY": "Revvity",
  "RWE.DE": "RWE",
  "SAF.PA": "Safran",
  "SAIC": "Science Applications International Corp",
  "SAN.PA": "Sanofi",
  "SAP.DE": "SAP",
  "SBAC": "SBA Communications",
  "SBUX": "Starbucks Corp",
  "SCHW": "Charles Schwab Corp",
  "SDR.L": "Schroders",
  "SGE.L": "Sage Group",
  "SGO.PA": "Saint-Gobain",
  "SHEL.L": "Shell",
  "SHL.DE": "Siemens Healthineers",
  "SHOP": "Shopify Inc",
  "SHW": "Sherwin-Williams Co",
  "SI=F": "Argent",
  "SIE.DE": "Siemens",
  "SJM": "J.M. Smucker Company (The)",
  "SKG.L": "Smurfit Kappa",
  "SLB": "Slb NV",
  "SMCI": "Super Micro Computer Inc",
  "SNA": "Snap-on",
  "SNAP": "Snap Inc",
  "SNDK": "Sandisk",
  "SNOW": "Snowflake Inc",
  "SNPS": "Synopsys Inc",
  "SO": "Southern Co",
  "SOL-USD": "Solana",
  "SOLV": "Solventum",
  "SPG": "Simon Property Group Inc",
  "SPGI": "S&P Global Inc",
  "SQ": "Block (Square)",
  "SRE": "Sempra",
  "SRT3.DE": "Sartorius",
  "SSE.L": "SSE",
  "STAN.L": "Standard Chartered",
  "STE": "Steris",
  "STLAM.MI": "Stellantis",
  "STLD": "Steel Dynamics",
  "STMPA.PA": "STMicroelectronics",
  "STT": "State Street Corporation",
  "STX": "Seagate Technology",
  "STZ": "Constellation Brands",
  "SU.PA": "Schneider Electric",
  "SVNL.L": "Serco",
  "SVT.L": "Severn Trent",
  "SW": "Smurfit Westrock",
  "SW.PA": "Sodexo",
  "SWK": "Stanley Black & Decker",
  "SWKS": "Skyworks Solutions",
  "SY1.DE": "Symrise",
  "SYF": "Synchrony Financial",
  "SYK": "Stryker Corp",
  "SYY": "Sysco",
  "T": "AT&T Inc",
  "TAP": "Molson Coors Beverage Company",
  "TDG": "TransDigm Group Inc",
  "TDY": "Teledyne Technologies",
  "TECH": "Bio-Techne",
  "TEL": "TE Connectivity",
  "TEP.PA": "Teleperformance",
  "TER": "Teradyne",
  "TFC": "Truist Financial",
  "TGT": "Target Corp",
  "TJX": "TJX Companies Inc",
  "TKO": "TKO Group Holdings",
  "TMO": "Thermo Fisher Scientific Inc",
  "TMUS": "T-Mobile US Inc",
  "TOL": "Toll Brothers Inc",
  "TPL": "Texas Pacific Land Corporation",
  "TPR": "\"Tapestry",
  "TRGP": "Targa Resources",
  "TRMB": "Trimble Inc",
  "TROW": "T. Rowe Price",
  "TRV": "Travelers Companies Inc",
  "TSCO": "Tractor Supply",
  "TSCO.L": "Tesco",
  "TSLA": "Tesla Inc",
  "TSN": "Tyson Foods",
  "TT": "Trane Technologies",
  "TTD": "Trade Desk (The)",
  "TTE.PA": "TotalEnergies",
  "TTWO": "Take-Two Interactive",
  "TXN": "Texas Instruments Inc",
  "TXT": "Textron",
  "TYL": "Tyler Technologies",
  "UAL": "United Airlines Holdings Inc",
  "UBER": "Uber Technologies Inc",
  "UDR": "\"UDR",
  "UHS": "Universal Health Services",
  "ULTA": "Ulta Beauty",
  "ULVR.L": "Unilever",
  "UNH": "UnitedHealth Group Inc",
  "UNP": "Union Pacific Corp",
  "UPS": "United Parcel Service Inc",
  "URI": "United Rentals",
  "URW.AS": "Unibail-Rodamco-Westfield",
  "USB": "US Bancorp",
  "USDCAD=X": "USD/CAD",
  "USDCHF=X": "USD/CHF",
  "USDJPY=X": "USD/JPY",
  "UU.L": "United Utilities",
  "V": "Visa Inc",
  "VICI": "Vici Properties",
  "VIE.PA": "Veolia",
  "VIV.PA": "Vivendi",
  "VLO": "Valero Energy Corp",
  "VLTO": "Veralto",
  "VMC": "Vulcan Materials Company",
  "VNA.DE": "Vonovia",
  "VOD.L": "Vodafone",
  "VOW3.DE": "Volkswagen",
  "VRSK": "Verisk Analytics Inc",
  "VRSN": "Verisign",
  "VRTX": "Vertex Pharmaceuticals Inc",
  "VST": "Vistra Corp.",
  "VTR": "Ventas",
  "VTRS": "Viatris",
  "VZ": "Verizon Communications Inc",
  "WAB": "Wabtec",
  "WAT": "Waters Corp",
  "WBA": "Walgreens Holding Co",
  "WBD": "Warner Bros. Discovery",
  "WDAY": "\"Workday",
  "WDC": "Western Digital",
  "WEC": "WEC Energy Group",
  "WEIR.L": "Weir Group",
  "WELL": "Welltower",
  "WFC": "Wells Fargo & Co",
  "WIZZ.L": "Wizz Air",
  "WLN.PA": "Worldline",
  "WM": "Waste Management Inc",
  "WMB": "Williams Companies",
  "WMT": "Walmart Inc",
  "WPP.L": "WPP",
  "WRB": "W. R. Berkley Corporation",
  "WSM": "\"Williams-Sonoma",
  "WST": "West Pharmaceutical Services",
  "WTW": "Willis Towers Watson",
  "WY": "Weyerhaeuser",
  "WYNN": "Wynn Resorts Ltd",
  "X": "United States Steel Corp",
  "XEL": "Xcel Energy",
  "XLE": "Energy ETF",
  "XLF": "Financials ETF",
  "XLK": "Tech ETF",
  "XOM": "Exxon Mobil Corp",
  "XRX.L": "Xaar",
  "XYL": "Xylem Inc.",
  "XYZ": "Block Inc.",
  "YUM": "Yum! Brands",
  "ZAL.DE": "Zalando",
  "ZBH": "Zimmer Biomet",
  "ZBRA": "Zebra Technologies",
  "ZS": "Zscaler Inc",
  "ZTS": "Zoetis Inc",
  "ZW=F": "Blé",
};

/** Symbol → editorial aliases (nicknames for narration variety) */
export const ASSET_ALIASES: Record<string, string[]> = {
  "^DJI": ["le Dow","le Dow Jones"],
  "^FCHI": ["le CAC","la Bourse de Paris"],
  "^FTSE": ["le FTSE","la City","Londres"],
  "^FVX": ["le cinq ans"],
  "^GDAXI": ["le DAX","Francfort"],
  "^GSPC": ["Wall Street","le S&P","l'indice américain"],
  "^HSI": ["le Hang Seng","Hong Kong"],
  "^IRX": ["le trois mois"],
  "^IXIC": ["le Nasdaq","la tech américaine"],
  "^KS11": ["le KOSPI","Séoul"],
  "^N225": ["le Nikkei","Tokyo"],
  "^STOXX": ["le Stoxx","les marchés européens"],
  "^TNX": ["le dix ans américain","le 10Y","le taux long"],
  "^TYX": ["le trente ans"],
  "^VIX": ["l'indice de la peur","le VIX","le baromètre de la peur"],
  "000001.SS": ["Shanghai","la Bourse de Shanghai"],
  "0700.HK": ["Tencent","le géant tech chinois"],
  "3690.HK": ["Meituan","le géant de la livraison chinois"],
  "399001.SZ": ["Shenzhen"],
  "6758.T": ["Sony"],
  "7203.T": ["Toyota","le premier constructeur mondial"],
  "7974.T": ["Nintendo"],
  "9984.T": ["SoftBank","le fonds Vision Fund"],
  "9988.HK": ["Alibaba","le Amazon chinois"],
  "AAPL": ["Apple","la pomme","le géant de Cupertino"],
  "ABBV": ["AbbVie"],
  "ABNB": ["Airbnb"],
  "AIR.PA": ["Airbus","l'avionneur européen"],
  "ALV.DE": ["Allianz","le premier assureur européen"],
  "AMD": ["AMD","Advanced Micro Devices"],
  "AMZN": ["Amazon","le géant du e-commerce"],
  "ARM": ["ARM","le fournisseur de plans de puces"],
  "AUDUSD=X": ["l'aussie"],
  "AVGO": ["Broadcom"],
  "AZN.L": ["AstraZeneca"],
  "BA": ["Boeing","l'avionneur américain"],
  "BAC": ["Bank of America","BofA"],
  "BATS.L": ["BAE Systems","le géant de la défense britannique"],
  "BKNG": ["Booking","Booking Holdings"],
  "BLK": ["BlackRock","le géant de la gestion","Larry Fink"],
  "BRK-B": ["Berkshire Hathaway","Buffett"],
  "BRK.B": ["Berkshire Hathaway","le conglomérat de Buffett","l'oracle d'Omaha"],
  "BTC-USD": ["le Bitcoin","le BTC","l'or numérique"],
  "BZ=F": ["le Brent","le brut de la mer du Nord"],
  "C": ["Citigroup","Citi"],
  "CAT": ["Caterpillar","le géant des engins"],
  "CL=F": ["le WTI","le brut américain","le baril"],
  "COIN": ["Coinbase","la plateforme crypto"],
  "COP": ["ConocoPhillips"],
  "COST": ["Costco"],
  "CRM": ["Salesforce"],
  "CRWD": ["CrowdStrike"],
  "CSCO": ["Cisco"],
  "CVX": ["Chevron"],
  "DE": ["Deere","John Deere"],
  "DIS": ["Disney","Walt Disney","la souris"],
  "DX-Y.NYB": ["le dollar","le billet vert","le roi dollar","le DXY"],
  "ETH-USD": ["l'Ethereum","l'ETH"],
  "EURGBP=X": ["l'euro-livre"],
  "EURJPY=X": ["l'euro-yen"],
  "EURUSD=X": ["l'euro-dollar","la paire reine"],
  "F": ["Ford"],
  "GBPJPY=X": ["la livre-yen"],
  "GBPUSD=X": ["le câble","la livre sterling"],
  "GC=F": ["l'or","le métal jaune","la relique barbare","le refuge ultime"],
  "GM": ["General Motors","GM"],
  "GOOG": ["Google","Alphabet"],
  "GOOGL": ["Google","Alphabet","la maison mère de Google"],
  "GS": ["Goldman Sachs","Goldman","la banque d'affaires"],
  "HD": ["Home Depot"],
  "HG=F": ["le cuivre","Dr Copper","le docteur Cuivre"],
  "HOOD": ["Robinhood"],
  "IBM": ["IBM","Big Blue"],
  "INTC": ["Intel","le fondeur historique"],
  "JNJ": ["Johnson & Johnson","J&J"],
  "JPM": ["JPMorgan","JPMorgan Chase","Jamie Dimon"],
  "KO": ["Coca-Cola","le géant d'Atlanta"],
  "LLY": ["Eli Lilly","Lilly"],
  "LMT": ["Lockheed Martin","le géant de la défense"],
  "MA": ["Mastercard"],
  "MC.PA": ["LVMH","le géant du luxe","Bernard Arnault"],
  "MCD": ["McDonald's","McDo"],
  "META": ["Meta","Facebook","la maison mère de Facebook","Zuckerberg"],
  "MRK": ["Merck"],
  "MRNA": ["Moderna"],
  "MS": ["Morgan Stanley"],
  "MSFT": ["Microsoft","le géant de Redmond"],
  "NFLX": ["Netflix"],
  "NG=F": ["le gaz naturel","le gaz"],
  "NOW": ["ServiceNow"],
  "NVDA": ["Nvidia","le roi de l'IA","le géant des GPU"],
  "NZDUSD=X": ["le kiwi"],
  "ORCL": ["Oracle"],
  "OXY": ["Occidental","Occidental Petroleum"],
  "PANW": ["Palo Alto Networks"],
  "PEP": ["PepsiCo","Pepsi"],
  "PFE": ["Pfizer"],
  "PL=F": ["le platine"],
  "PLTR": ["Palantir","le spécialiste du big data"],
  "PYPL": ["PayPal"],
  "QCOM": ["Qualcomm"],
  "RHM.DE": ["Rheinmetall","le groupe de défense allemand"],
  "RMS.PA": ["Hermès","la maison Hermès"],
  "RR.L": ["Rolls-Royce","le motoriste britannique"],
  "RTX": ["Raytheon","RTX"],
  "SAN.PA": ["Sanofi","le géant pharmaceutique français"],
  "SAP.DE": ["SAP","le géant du logiciel européen"],
  "SBUX": ["Starbucks"],
  "SHEL.L": ["Shell","la major anglo-néerlandaise"],
  "SI=F": ["l'argent","le métal gris"],
  "SIE.DE": ["Siemens"],
  "SLB": ["Schlumberger","le leader des services pétroliers"],
  "SMCI": ["Super Micro","Supermicro"],
  "SOL-USD": ["Solana","le SOL"],
  "T": ["AT&T"],
  "TMUS": ["T-Mobile"],
  "TSLA": ["Tesla","le constructeur d'Elon Musk"],
  "TTE.PA": ["TotalEnergies","Total","la major française"],
  "TXN": ["Texas Instruments","TI"],
  "UBER": ["Uber"],
  "UNH": ["UnitedHealth","le géant de l'assurance santé"],
  "USDCAD=X": ["le loonie"],
  "USDCHF=X": ["le dollar-franc suisse"],
  "USDJPY=X": ["le dollar-yen"],
  "V": ["Visa"],
  "VZ": ["Verizon"],
  "WFC": ["Wells Fargo"],
  "WMT": ["Walmart","le géant de la distribution"],
  "XLE": ["le secteur énergie","l'ETF énergie"],
  "XLF": ["le secteur financier","l'ETF financier"],
  "XLK": ["le secteur tech","l'ETF tech"],
  "XOM": ["ExxonMobil","Exxon","la major pétrolière"],
  "ZW=F": ["le blé"],
};

/** Symbol → one-line description (for LLM context) */
export const ASSET_DESCRIPTIONS: Record<string, string> = {
  "^DJI": "30 blue-chip US stocks, oldest market barometer",
  "^FCHI": "French benchmark index of 40 largest Paris-listed companies",
  "^FTSE": "UK benchmark index of 100 largest London-listed companies",
  "^FVX": "US 5-year Treasury yield, medium-term rate benchmark",
  "^GDAXI": "German benchmark index of 40 largest Frankfurt-listed companies",
  "^GSPC": "US benchmark index of 500 largest companies, Wall Street barometer",
  "^HSI": "Hong Kong benchmark index of 30 largest listed companies",
  "^IRX": "US 3-month Treasury bill yield, short-term rate proxy",
  "^IXIC": "US tech-heavy index, growth stocks benchmark",
  "^KS11": "South Korean benchmark stock index",
  "^N225": "Japanese benchmark index of 225 Tokyo-listed companies",
  "^STOXX": "Pan-European index covering 600 companies across 17 countries",
  "^TNX": "US 10-year Treasury yield, global risk-free rate benchmark",
  "^TYX": "US 30-year Treasury yield, long-duration rate benchmark",
  "^VIX": "Market fear gauge derived from S&P 500 options",
  "000001.SS": "Chinese mainland stock index, barometer of China domestic market",
  "0001.HK": "Li Ka-shing's conglomerate — ports, telecoms, retail, energy, infrastructure",
  "0002.HK": "Hong Kong electric utility, power generation across Asia-Pacific",
  "0003.HK": "Hong Kong & mainland China gas distribution, oldest utility in HK",
  "0005.HK": "Global bank headquartered in London, major Asia/Europe presence",
  "0006.HK": "International power investment holding, Li Ka-shing group",
  "0011.HK": "Major Hong Kong retail bank, subsidiary of HSBC",
  "0012.HK": "Major Hong Kong property developer, residential & commercial",
  "0016.HK": "Hong Kong's largest property developer by market cap",
  "0017.HK": "Hong Kong property developer, also hotels & infrastructure",
  "0388.HK": "Operator of Hong Kong Stock Exchange, connects global capital to China",
  "0669.HK": "Power tools maker (Milwaukee, Ryobi brands), HK-based global manufacturer",
  "0688.HK": "One of China's largest state-backed property developers",
  "0700.HK": "Chinese tech giant — social media (WeChat), gaming, cloud, fintech",
  "0762.HK": "China's second-largest mobile operator, state-owned telecom",
  "0883.HK": "China's largest offshore oil & gas producer, major crude explorer",
  "0939.HK": "One of China's Big Four state-owned banks, infrastructure lending",
  "0941.HK": "China's largest mobile telecom operator, 950M+ subscribers",
  "0960.HK": "Chinese private property developer, also mall operator",
  "1038.HK": "Global infrastructure group — utilities, transport, waste, Li Ka-shing empire",
  "1093.HK": "Chinese pharmaceutical company, generics & innovative drugs",
  "1177.HK": "Chinese pharmaceutical group, oncology & hepatitis drugs",
  "1299.HK": "Asia's largest life insurance group, 18 markets across Asia-Pacific",
  "1398.HK": "Industrial & Commercial Bank of China — world's largest bank by assets",
  "1COV.DE": "German specialty chemicals, polycarbonates & polyurethanes, ex-Bayer",
  "2269.HK": "Chinese biotech contract manufacturer (CDMO), global biologics outsourcing",
  "2318.HK": "China's largest private insurer, also fintech/healthtech conglomerate",
  "2382.HK": "Chinese optical lens & camera module maker, supplier to smartphone OEMs",
  "3382.T": "Parent of 7-Eleven convenience stores, world's largest convenience chain",
  "3690.HK": "China's leading food delivery, local services & e-commerce platform",
  "399001.SZ": "Chinese tech-heavy stock index, Shenzhen exchange",
  "4063.T": "World's largest producer of PVC & silicon wafers for semiconductors",
  "4502.T": "Japan's largest pharma company, global presence in GI, oncology, neuroscience",
  "4507.T": "Japanese pharmaceutical, HIV treatments & infectious disease focus",
  "4519.T": "Japanese pharma, majority-owned by Roche, oncology & antibody drugs",
  "4543.T": "Japanese medical devices maker, cardiovascular & blood management systems",
  "4568.T": "Japanese pharma, breakthrough antibody-drug conjugates (Enhertu with AstraZeneca)",
  "4661.T": "Operator of Tokyo Disney Resort (Disneyland & DisneySea)",
  "4704.T": "Japanese-American cybersecurity company, enterprise antivirus & cloud security",
  "4911.T": "Japan's largest cosmetics company, luxury skincare & beauty, global brand",
  "5108.T": "World's largest tire manufacturer, Japanese multinational",
  "6098.T": "Japanese HR & staffing conglomerate, owns Indeed and Glassdoor",
  "6273.T": "World leader in pneumatic automation components, factory equipment",
  "6367.T": "World's largest air conditioning manufacturer, Japanese HVAC leader",
  "6501.T": "Japanese industrial conglomerate — power grids, trains, IT infrastructure",
  "6752.T": "Japanese electronics group, major Tesla battery supplier (EV batteries)",
  "6758.T": "Japanese electronics/entertainment conglomerate — PlayStation, music, films, sensors",
  "6861.T": "Japanese industrial automation & sensors maker, extremely high margins",
  "6902.T": "World's second-largest auto parts supplier, Toyota affiliate, EV components",
  "6954.T": "World leader in industrial robots & CNC machine tools, factory automation",
  "7011.T": "Japanese defense, energy & aerospace conglomerate — turbines, ships, rockets",
  "7203.T": "World's largest automaker by volume, Japan's flagship manufacturer",
  "7267.T": "Japanese automaker & motorcycle manufacturer, also robotics & aviation",
  "7733.T": "Japanese medical endoscopy world leader (~70% global share), formerly cameras",
  "7741.T": "Japanese optics maker — eyeglass lenses, semiconductor photomasks, endoscopes",
  "7832.T": "Japanese entertainment — toys (Gundam), video games (Tekken, Elden Ring), anime",
  "7974.T": "Japanese gaming giant — Switch console, Mario/Zelda/Pokemon franchises",
  "8031.T": "Japanese trading house (sogo shosha), commodities, energy, infrastructure",
  "8035.T": "World's third-largest semiconductor equipment maker, critical chip tooling",
  "8053.T": "Japanese trading house, metals, transport, infrastructure, media, real estate",
  "8058.T": "Japan's largest trading house, commodities, metals, energy, food, chemicals",
  "8306.T": "Japan's largest bank (MUFG), global investment banking & retail",
  "8316.T": "Japan's second-largest banking group (SMFG), retail & wholesale banking",
  "8801.T": "Japan's largest real estate developer, office buildings, malls, residential",
  "9020.T": "Japan's largest rail operator (JR East), Tokyo metropolitan trains + Shinkansen",
  "9022.T": "Operator of Tokaido Shinkansen (Tokyo-Osaka bullet train), JR Central",
  "9432.T": "Nippon Telegraph & Telephone — Japan's largest telecom, global IT services",
  "9433.T": "Japan's second-largest telecom operator (au mobile brand)",
  "9613.T": "Japanese IT services & consulting, NTT subsidiary, global digital transformation",
  "9618.HK": "Chinese e-commerce & logistics giant, direct retail model (vs Alibaba marketplace)",
  "9984.T": "Japanese tech conglomerate & venture capital (Vision Fund), owns ARM Holdings",
  "9988.HK": "Chinese e-commerce leader (Taobao, Tmall), cloud computing, logistics",
  "9999.HK": "Chinese gaming & internet company, rival to Tencent in online games",
  "A": "Lab instruments and consumables for DNA sequencing, diagnostics, drug discovery worldwide",
  "AA": "Largest US aluminum producer, supplies aerospace, automotive, packaging industries",
  "AAL": "Major US airline, regional/domestic hub model, leisure and business travel",
  "AAL.L": "South African-British mining giant — diamonds (De Beers), copper, platinum, iron ore",
  "AAPL": "World's most valuable company, iPhones, Macs, services ecosystem",
  "ABBV": "Pharmaceutical giant spun from AbbVie, oncology and immunology focus",
  "ABNB": "Peer-to-peer vacation rental platform, alternative to hotels globally",
  "ABT": "Healthcare giant, diagnostic devices, medical equipment, generic drugs",
  "ACA.PA": "Première banque de détail en France, aussi assurance & gestion d'actifs",
  "ACGL": "Reinsurance company covering catastrophe and property losses worldwide",
  "ACN": "Global IT consulting and outsourcing firm, cloud and digital transformation",
  "ADBE": "Software leader, Photoshop and Creative Cloud, enterprise analytics with Figma",
  "ADI": "Analog chip designer, power management and signal processing for industrial IoT",
  "ADM": "Agricultural commodities processor, grains, oils, animal feed, biofuels",
  "ADP": "HR outsourcing payroll processor for millions of US businesses annually",
  "ADS.DE": "German sportswear giant, world's second-largest after Nike",
  "ADSK": "Design software for architecture, engineering, construction, media industries",
  "AEE": "Utility company providing electricity to Missouri and Illinois regions",
  "AEP": "Major US electric utility, central and midwest regional power distribution",
  "AES": "Global energy and infrastructure company, renewable power and electricity distribution",
  "AFL": "Japanese-founded insurance, accident coverage, strong US military presence",
  "AI.PA": "Leader mondial des gaz industriels & médicaux, fournisseur hydrogène",
  "AIG": "Mega insurance conglomerate, property, life, accident coverage globally",
  "AIR.DE": "European aircraft manufacturer, Boeing's main rival, also defense & space",
  "AIR.PA": "Constructeur aéronautique européen, rival de Boeing, aussi défense & spatial",
  "AIZ": "Insurance company, property and casualty, renters, mobile home coverage",
  "AJG": "Insurance broker and risk management, commercial and personal lines consultant",
  "AKAM": "Content delivery network and cybersecurity, edge computing infrastructure",
  "ALB": "Chemical company, lithium mining for batteries, bromine, specialty chemicals",
  "ALGN": "Invisalign clear braces and digital orthodontics technology",
  "ALK": "Alaska's major airline, West Coast regional service, leisure and business",
  "ALL": "Insurance company, auto and home coverage, large regional player USA",
  "ALLE": "Smart locks and access control systems, residential and commercial security",
  "ALV.DE": "Europe's largest insurer, also asset management (PIMCO)",
  "AMAT": "Semiconductor equipment manufacturer, chip production machinery leader",
  "AMCR": "Packaging materials company, flexible and rigid plastic food packaging",
  "AMD": "CPU and GPU chipmaker rivaling Intel, AI accelerators, data center chips",
  "AME": "Industrial electronics and sensors, precision instruments for manufacturing",
  "AMGN": "Biotech pharmaceutical, oncology, cardiovascular, immunology focus",
  "AMP": "Financial advisory and wealth management for high-net-worth individuals",
  "AMT": "Real estate investment trust, cell towers and broadcast infrastructure owner",
  "AMZN": "E-commerce, cloud computing, streaming, and digital advertising giant",
  "ANET": "High-speed networking switches and software, data center cloud infrastructure",
  "ANTO.L": "Chilean-British copper miner, three mines in Chile, Luksic family",
  "AON": "Insurance and risk management consulting, benefits and compensation advisor",
  "AOS": "A. O. Smith manufactures water heaters and treatment systems",
  "APA": "Oil and gas exploration and production, US onshore assets",
  "APD": "Industrial gases, hydrogen, oxygen, nitrogen for manufacturing and energy",
  "APH": "Electrical connectors and sensors for aerospace, automotive, IT infrastructure",
  "APO": "Alternative asset manager, private equity, credit, real estate investor",
  "APP": "Mobile gaming platform, advertising software, games and app monetization",
  "APTV": "Automotive parts supplier, autonomous vehicles, active safety technology",
  "ARE": "Life sciences real estate owner, biotech parks, lab buildings",
  "ARES": "Alternative asset manager, credit, infrastructure, private equity funds",
  "ARM": "Semiconductor IP design, ARM processors power iPhones, most phones globally",
  "ATO": "Natural gas utility, supplies households and businesses southeastern US",
  "AUDUSD=X": "Australian Dollar vs USD, commodity currency proxy",
  "AVB": "Multifamily apartments owner, residential real estate investment trust",
  "AVGO": "Semiconductor company, broadcom infrastructure, wireless and networking chips",
  "AVY": "Specialty materials, adhesive labels, packaging films and ID solutions",
  "AWK": "Regional water utility, supplies households and businesses New Jersey area",
  "AXA.PA": "Premier assureur européen, assurance vie, dommages & gestion d'actifs",
  "AXON": "Law enforcement technology, tasers and body cameras, surveillance software",
  "AXP": "American Express, payment processor and lender, premium credit cards",
  "AZN.L": "British-Swedish pharma giant, oncology & rare diseases, COVID vaccine",
  "AZO": "Aftermarket automotive parts retailer, DIY and professional mechanics",
  "BA": "Boeing, commercial aircraft, defense systems, space exploration contractor",
  "BAC": "Bank of America, major US bank, lending, deposits, wealth management",
  "BALL": "Aluminum beverage cans and containers, food and drink packaging leader",
  "BAS.DE": "World's largest chemical company, German industrial cornerstone",
  "BAT.L": "World's second-largest tobacco company, also vaping & heated products",
  "BATS.L": "UK's largest defense contractor, fighter jets, submarines, cybersecurity",
  "BAX": "Baxter medical devices, IV solutions, renal care, medications",
  "BAYN.DE": "German pharma & crop science group, acquired Monsanto, Roundup litigation",
  "BBY": "Consumer electronics retailer, computers, appliances, Geek Squad services",
  "BDX": "Medical devices and diagnostic company, blood collection, needles, syringes",
  "BEI.DE": "German skincare company — Nivea, Eucerin, La Prairie brands",
  "BEN": "Franklin Templeton mutual funds and ETFs, asset management company",
  "BF.B": "Brown-Forman bourbon and whiskey distiller, Jack Daniel's owner",
  "BG": "Bunge grains and agriculture, soy, wheat, sugar commodity processing",
  "BIIB": "Biogen biotech, Alzheimer's disease, multiple sclerosis, neurodegenerative focus",
  "BIO": "Biorad lab diagnostics equipment, clinical chemistry and immunohematology",
  "BK": "BNY Mellon asset manager and custodian, institutional money and securities",
  "BKNG": "Booking online travel agency, hotels, flights, vacation rentals platform",
  "BKR": "Baker Hughes oil and gas equipment, turbomachinery, drilling services",
  "BLDR": "Builders FirstSource lumber, building materials supplier to contractors",
  "BLK": "BlackRock investment manager, largest ETF provider, $10+ trillion assets",
  "BMW.DE": "German premium automaker — BMW, Mini, Rolls-Royce cars",
  "BMY": "Bristol Myers Squibb pharma, oncology, immunology, cardiovascular drugs",
  "BN.PA": "Groupe alimentaire français — produits laitiers, eaux, nutrition médicale",
  "BNP.PA": "Première banque de la zone euro par actifs, banque universelle mondiale",
  "BNR.DE": "World's largest chemical distributor, middleman between producers & industries",
  "BP.L": "British oil & gas major, one of world's top 5 energy supermajors",
  "BR": "Broadridge financial outsourcing, investment management, compliance software",
  "BRK-B": "Berkshire Hathaway conglomerate, insurance, energy, rails, utilities",
  "BRK.B": "Berkshire Hathaway conglomerate, insurance, energy, rails, utilities",
  "BRO": "Brown and Brown insurance broker, commercial and personal risk consultant",
  "BSX": "Boston Scientific medical devices, stents, pacemakers, surgical tools",
  "BT-A.L": "UK's largest fixed-line telecom, broadband (Openreach) & mobile (EE)",
  "BTC-USD": "First and largest cryptocurrency, digital gold narrative",
  "BX": "Blackstone private equity and alternatives, real estate, infrastructure funds",
  "BXP": "Boston Properties office and real estate investment trust, urban properties",
  "BZ=F": "Brent crude oil futures, international oil benchmark",
  "C": "Citigroup mega bank, investment banking, trading, lending, wealth management",
  "CA.PA": "Deuxième distributeur européen, hypermarchés & supermarchés dans 30 pays",
  "CAG": "Conagra Brands foods, frozen meals, spices, Birds Eye, Marie Callender's",
  "CAH": "Cardinal Health pharmaceutical distributor and medical supplies wholesaler",
  "CAP.PA": "Leader français du conseil & services IT, transformation digitale des entreprises",
  "CARR": "Carrier HVAC systems and refrigeration, climate control leader globally",
  "CAT": "Caterpillar heavy equipment manufacturer, earthmoving, mining, construction",
  "CB": "Chubb insurance company, property, casualty, marine, specialty coverage",
  "CBK.DE": "Germany's second-largest commercial bank, corporate & SME focus",
  "CBOE": "Cboe stock exchange and derivatives, options trading and market data",
  "CBRE": "CBRE real estate services, commercial property leasing and management",
  "CCI": "Crown Castle cell tower and data center real estate investment trust",
  "CCL": "Carnival cruise line operator, leisure travel entertainment at sea",
  "CDNS": "Cadence semiconductor design software, chip development tools",
  "CDW": "Computer hardware and software distributor to businesses and government",
  "CE": "Celanese chemicals and engineered materials, acetyl, specialty plastics",
  "CEG": "Constellation Energy nuclear power operator, emissions-free electricity",
  "CF": "CF Industries fertilizer producer, ammonia and urea for agriculture",
  "CFG": "Citizens Financial regional bank, commercial and consumer lending",
  "CHD": "Church and Dwight baking soda company, Arm and Hammer consumer products",
  "CHRW": "C.H. Robinson logistics and freight broker, supply chain management",
  "CHTR": "Charter Communications cable provider, broadband, TV, internet",
  "CI": "Cigna health insurance company, medical and pharmacy coverage",
  "CIEN": "Ciena optical networking systems, long-distance telecommunications fiber",
  "CINF": "Cincinnati Financial insurance, property and casualty, regional carrier",
  "CL": "Colgate-Palmolive toothpaste and personal care, oral hygiene leader",
  "CL=F": "West Texas Intermediate crude oil futures, US oil benchmark",
  "CLF": "Cleveland-Cliffs iron ore and steel, North American steelmaker",
  "CLX": "Clorox bleach and cleaning products, Kingsford charcoal, Hidden Valley",
  "CMCSA": "Comcast cable TV, internet, phone provider, NBCUniversal media owner",
  "CME": "CME Group futures and derivatives exchange, agricultural and financial contracts",
  "CMG": "Chipotle Mexican Grill fast-casual restaurant, fresh ingredients model",
  "CMI": "Diesel engine and power systems manufacturer for trucks, construction, mining equipment",
  "CMS": "Michigan utility providing electricity and natural gas to regional customers",
  "CNA.L": "UK energy supplier (British Gas), also power generation & nuclear",
  "CNC": "Health insurance company serving Medicaid, Medicare, and marketplace customers",
  "CNP": "Texas energy company providing electricity and natural gas distribution",
  "COF": "Credit card and consumer finance lender issuing branded credit products",
  "COIN": "Cryptocurrency exchange platform for buying, selling, and holding digital assets",
  "CON.DE": "German auto parts & tire manufacturer, autonomous driving tech",
  "COO": "Surgical equipment manufacturer specializing in vision care and gynecology devices",
  "COP": "Major oil and natural gas explorer and producer with global reserves",
  "COR": "Largest pharmaceutical and healthcare distributor in North America",
  "COST": "Membership warehouse club with bulk retail sales model, consumer staples",
  "CPAY": "Payment technology company processing B2B and corporate transactions",
  "CPB": "Food company making soup, snacks, and shelf-stable branded consumer products",
  "CPG.L": "World's largest contract foodservice company, workplace & hospital catering",
  "CPRT": "Online insurance auction platform for salvage and damaged vehicles",
  "CPT": "Real estate trust owning multifamily apartments in US Sun Belt markets",
  "CRH": "Irish building materials company making concrete, aggregates, asphalt, stone",
  "CRL": "Contract research organization conducting preclinical and clinical drug testing",
  "CRM": "Cloud CRM software for sales, service, marketing, and analytics",
  "CRWD": "Endpoint security software detecting and preventing cyberattacks on devices",
  "CSCO": "Networking equipment and software company for enterprise IT infrastructure",
  "CSGP": "Commercial real estate information platform and analytics software",
  "CSX": "Freight railroad operating major rail network across eastern United States",
  "CTAS": "Uniform rental and facility services company cleaning and supplying workplaces",
  "CTRA": "Oil and natural gas producer operating in Appalachian and Delaware basins",
  "CTSH": "IT services and consulting firm providing digital transformation and outsourcing",
  "CTVA": "Agricultural biotechnology company making seeds and crop protection chemicals",
  "CVNA": "Online used car retailer buying, selling, and financing vehicles",
  "CVS": "Pharmacy and health care services chain with retail clinics and insurance",
  "CVX": "Global oil and gas producer with major exploration and refining operations",
  "D": "Utility providing electricity and natural gas to southeastern US customers",
  "DAL": "Major US airline operating domestic and international passenger flights",
  "DASH": "Food delivery platform connecting restaurants with customers and drivers",
  "DB1.DE": "Operator of Frankfurt Stock Exchange, Eurex derivatives, Clearstream",
  "DBK.DE": "Germany's largest bank, investment banking & asset management",
  "DD": "Specialty chemicals company making polymers, pigments, coatings, agriculture products",
  "DDOG": "Cloud monitoring and analytics software for infrastructure and applications",
  "DE": "Equipment manufacturer making agricultural machinery and construction equipment",
  "DECK": "Footwear and apparel company known for premium outdoor and casual shoes",
  "DELL": "Computer hardware manufacturer making desktops, laptops, and server systems",
  "DG": "Discount retailer operating convenience stores in rural and underserved markets",
  "DG.PA": "Numéro un mondial du BTP & concessions (autoroutes, aéroports)",
  "DGE.L": "World's largest spirits company — Johnnie Walker, Guinness, Smirnoff, Tanqueray",
  "DGX": "Clinical laboratory company providing diagnostic testing and health screening",
  "DHER.DE": "German food delivery platform, operates in 70+ countries (not in Germany itself)",
  "DHI": "Homebuilder constructing single-family homes in US residential markets",
  "DHL.DE": "World's largest logistics company (ex-Deutsche Post), express, freight, supply chain",
  "DHR": "Diversified science and technology conglomerate with life sciences and diagnostics",
  "DIS": "Entertainment company producing films, TV shows, streaming content, theme parks",
  "DLR": "Data center real estate company leasing colocation space to tech companies",
  "DLTR": "Discount retailer selling discounted household items, toys, and seasonal goods",
  "DOC": "Healthcare real estate trust owning medical office buildings and facilities",
  "DOV": "Industrial manufacturer making equipment for refrigeration, fluid handling, fueling",
  "DOW": "Chemical manufacturer making plastics, coatings, agriculture products, materials",
  "DPZ": "Pizza delivery company with largest delivery pizza chain in North America",
  "DRI": "Restaurant operator running casual dining chains like Olive Garden, Longhorn",
  "DSY.PA": "Leader mondial des logiciels de modélisation 3D & PLM (CATIA, SolidWorks)",
  "DTE": "Michigan utility providing electricity and natural gas to regional customers",
  "DTE.DE": "Europe's largest telecom by revenue, majority owner of T-Mobile US",
  "DUK": "Major utility providing electricity and natural gas to Carolinas and Florida",
  "DVA": "Kidney dialysis services company providing treatment for end-stage renal disease",
  "DVN": "Oil and natural gas producer with operations in onshore US shale plays",
  "DX-Y.NYB": "Trade-weighted USD index against 6 major currencies",
  "DXCM": "Continuous glucose monitoring company making wearable diabetes management devices",
  "EA": "Video game publisher making sports, action, simulation games for multiple platforms",
  "EBAY": "Online marketplace connecting buyers and sellers for auctions and fixed-price sales",
  "ECL": "Cleaning and hygiene company providing chemicals and services for industrial customers",
  "ED": "Utility providing electricity and natural gas to New York City area",
  "EFX": "Credit reporting agency collecting and managing consumer financial data",
  "EG": "Reinsurance company providing catastrophe and excess insurance to insurers",
  "EIX": "Utility providing electricity to California customers, wildfire risk exposure",
  "EL": "Luxury cosmetics and skincare company making premium beauty and wellness products",
  "EL.PA": "Leader mondial de l'optique — verres Essilor + lunettes Luxottica (Ray-Ban)",
  "ELV": "Health insurance company serving Medicaid, Medicare, and marketplace customers",
  "EME": "Mechanical systems contractor providing HVAC, plumbing, electrical services",
  "EMR": "Diversified manufacturer making climate control, valve, and automation systems",
  "EN.PA": "Conglomérat français — BTP, télécom (Bouygues Telecom), médias (TF1)",
  "ENGI.PA": "Groupe énergétique français, gaz naturel, renouvelables, réseaux de chaleur",
  "ENR.DE": "German energy technology — gas turbines, wind (Gamesa), grid solutions",
  "EOAN.DE": "Major German utility, electricity & gas distribution, energy networks",
  "EOG": "Oil and natural gas producer with unconventional resource focus",
  "EPAM": "IT services and software engineering company providing digital transformation services",
  "EQIX": "Data center real estate company with global colocation and interconnection services",
  "EQR": "Residential real estate trust owning apartment communities in US markets",
  "EQT": "Natural gas producer and midstream company with Appalachian operations",
  "ERF.PA": "Leader mondial des services d'analyses (alimentaire, pharma, environnement)",
  "ERIE": "Regional property and casualty insurance company serving homeowners and auto",
  "ES": "Utility providing electricity and natural gas to New England customers",
  "ESS": "California residential real estate trust owning and operating apartment communities",
  "ETH-USD": "Second-largest crypto, smart contract platform, DeFi backbone",
  "ETN": "Industrial manufacturer making electrical equipment and power distribution systems",
  "ETR": "Utility providing electricity to Gulf Coast and mid-south US customers",
  "EURGBP=X": "Euro vs British Pound cross rate",
  "EURJPY=X": "Euro vs Japanese Yen cross rate",
  "EURUSD=X": "Euro vs US Dollar, world's most traded currency pair",
  "EVRG": "Kansas and Oklahoma utility providing electricity and natural gas services",
  "EW": "Medical device company making cardiac, structural, and neurovascular devices",
  "EXC": "Major utility providing electricity and natural gas to mid-Atlantic customers",
  "EXE": "Energy company developing and operating renewable power generation projects",
  "EXPD": "Freight forwarding and logistics company handling air, ocean, and ground shipping",
  "EXPE": "Online travel company offering hotel, flight, and vacation rental bookings",
  "EXPN.L": "World's largest credit bureau, consumer & business credit data",
  "EXR": "Self-storage real estate trust operating climate-controlled storage facilities",
  "EZJ.L": "UK's largest low-cost airline, European short-haul",
  "F": "Automaker designing, manufacturing, selling cars, trucks, and commercial vehicles",
  "FANG": "Oil and gas producer focused on shale reserves in Permian Basin",
  "FAST": "Industrial fasteners and tools distributor serving construction and manufacturing",
  "FCX": "Copper mining company with operations in Peru, Indonesia, and United States",
  "FDS": "Financial data and analytics company providing investment research and tools",
  "FDX": "Global logistics company delivering packages and freight for businesses and consumers",
  "FE": "Utility providing electricity to Ohio, Pennsylvania, West Virginia customers",
  "FERG.L": "World's largest plumbing & HVAC distributor, mainly US operations",
  "FFIV": "Application delivery controller providing network security and optimization software",
  "FICO": "Credit scoring company providing decision analytics for lending and fraud detection",
  "FIS": "Financial services software company providing banking, payments, trading systems",
  "FISV": "Financial software company processing payments and managing banking systems",
  "FITB": "Regional bank providing consumer and commercial banking services",
  "FIX": "HVAC and electrical services company for commercial and industrial customers",
  "FLTR.L": "World's largest online sports betting group — FanDuel, Paddy Power, Betfair",
  "FOX": "Media company producing and broadcasting entertainment and news programming",
  "FOXA": "Media company producing and broadcasting entertainment and news content",
  "FRE.DE": "German healthcare group — hospitals, dialysis (Fresenius Medical Care), nutrition",
  "FRT": "Real estate trust owning shopping centers and outdoor malls nationwide",
  "FSLR": "Solar panel manufacturer making photovoltaic modules for utility and residential",
  "FTNT": "Cybersecurity company making firewalls and network security appliances",
  "FTV": "Industrial technology conglomerate making precision equipment and software solutions",
  "GBPJPY=X": "British Pound vs Yen, high-volatility carry pair",
  "GBPUSD=X": "British Pound vs US Dollar",
  "GC=F": "Gold futures, ultimate safe-haven asset and inflation hedge",
  "GD": "Defense contractor making military aircraft, missiles, and surveillance systems",
  "GDDY": "Web hosting and domain registration company serving small business websites",
  "GE": "Industrial conglomerate making power, aviation, renewable energy equipment",
  "GEHC": "Medical devices company making imaging, monitoring, and diagnostics equipment",
  "GEN": "Cybersecurity software company providing endpoint protection and threat detection",
  "GEV": "Energy infrastructure company providing grid modernization and energy storage",
  "GILD": "HIV and hepatitis C antivirals, oncology drugs—global pharma giant",
  "GIS": "Breakfast cereals, yogurt, pet food—packaged consumer staples brand",
  "GL": "Life insurance and annuities—financial security for working Americans",
  "GLE.PA": "Grande banque française, banque de détail, financement & marchés",
  "GLEN.L": "Swiss-British commodities trader & miner — copper, cobalt, zinc, coal, oil",
  "GLW": "Glass and ceramics for tech, automotive, industrial applications worldwide",
  "GM": "Trucks, cars, electric vehicles—America's largest automaker by volume",
  "GNRC": "Backup generators for homes and businesses during power outages",
  "GOOG": "Search, ads, cloud, Android—world's dominant advertising and data platform",
  "GOOGL": "Search, ads, cloud, Android—world's dominant advertising and data platform",
  "GPC": "Auto parts, tools, supplies distribution to mechanics and retailers",
  "GPN": "Digital payment processing and commerce infrastructure for merchants",
  "GRMN": "GPS watches, navigation, marine electronics for outdoors and aviation",
  "GS": "Investment banking, trading, wealth management—Wall Street powerhouse",
  "GSK.L": "British pharma (ex-GlaxoSmithKline), vaccines, specialty medicines",
  "GWW": "Industrial equipment and supplies distribution to business and construction",
  "H": "Luxury hotel chain—Park Hyatt, Hyatt, Andaz, other premium brands",
  "HAL": "Oil and gas drilling services, equipment, chemicals for energy sector",
  "HAS": "Toy manufacturer—Play-Doh, Transformers, My Little Pony, board games",
  "HBAN": "Regional bank headquartered in Columbus, Ohio—consumer and commercial loans",
  "HCA": "Hospital operator—largest private healthcare chain in United States",
  "HD": "Hardware and home improvement retail—orange-badged DIY superstore",
  "HEI.DE": "Major global cement & building materials producer (ex-HeidelbergCement)",
  "HFG.DE": "World's largest meal kit delivery company, German-founded",
  "HG=F": "Copper futures, industrial bellwether and economic health indicator",
  "HIG": "Property and casualty insurance—risk management for businesses and homes",
  "HII": "Military shipbuilder—submarines, destroyers, aircraft carriers for Navy",
  "HLN.L": "Consumer health spinoff from GSK — Sensodyne, Advil, Voltaren, Centrum",
  "HLT": "Hotel franchiser—Hilton, DoubleTree, Hampton across luxury and midscale",
  "HNR1.DE": "World's third-largest reinsurer, property/casualty & life/health",
  "HO.PA": "Groupe français de défense, aérospatial, cybersécurité & transport",
  "HOLX": "Women's health diagnostics and breast imaging devices and software",
  "HON": "Aerospace, building controls, safety equipment—diversified industrial",
  "HOOD": "Retail brokerage platform—commission-free stocks, options, crypto trading",
  "HPE": "Enterprise IT infrastructure—servers, storage, networking for data centers",
  "HPQ": "Desktop and laptop computers plus printers—consumer and business tech",
  "HRL": "Canned meat, bacon, pepperoni—iconic American processed meat brand",
  "HSBA.L": "Europe's largest bank, headquarters London, dominant in Asia",
  "HSIC": "Dental and healthcare supplies distributor to practitioners worldwide",
  "HST": "Luxury hotel real estate REIT—owns Marriott and Hyatt properties",
  "HSY": "Chocolate and candy manufacturer—Hershey's, Reese's, Kisses iconic brands",
  "HUBB": "Electrical and utility products, power distribution, industrial connectors",
  "HUM": "Medicare Advantage and managed healthcare plans for elderly and disabled",
  "HWM": "Aerospace aluminum and metal parts—jet engines, defense, commercial planes",
  "IAG.L": "International Airlines Group — British Airways, Iberia, Vueling, Aer Lingus",
  "IBKR": "Discount broker for professionals—trading, prime brokerage, wealth management",
  "IBM": "Enterprise IT services, cloud, AI software—legacy tech infrastructure provider",
  "ICE": "Stock exchange operator—NYSE, commodity futures, data and analytics",
  "IDXX": "Animal health diagnostics and software for veterinary clinics worldwide",
  "IEX": "Fluid power and motion control systems for industrial manufacturing",
  "IFF": "Flavors, fragrances, cosmetic ingredients for food and beauty industries",
  "IFX.DE": "German semiconductor maker, leader in automotive chips & power semiconductors",
  "IHG.L": "British hotel group — Holiday Inn, Crowne Plaza, Six Senses, 6000+ hotels",
  "III.L": "British private equity & infrastructure investor, owns Action discount stores",
  "ILMN": "DNA sequencing technology—genetic testing, cancer research, precision medicine",
  "IMB.L": "British tobacco company — Winston, Davidoff, Gauloises",
  "INCY": "Oncology and immunology drugs—JAK inhibitors for blood cancers",
  "INTC": "Semiconductor chips—processors for PCs, servers, data center computing",
  "INTU": "Tax software (TurboTax), accounting (QuickBooks)—finance for individuals",
  "INVH": "Single-family home rental REIT—manages residential properties nationwide",
  "IP": "Cardboard, packaging, pulp paper—corrugated boxes for shipping and commerce",
  "IQV": "Clinical trial services and healthcare data analytics for pharmaceutical companies",
  "IR": "Diversified industrial—compressors, air handlers, controls, aftermarket services",
  "IRM": "Data center and records management REIT—physical document and data storage",
  "ISRG": "Robotic surgery systems (da Vinci)—surgical automation for hospitals",
  "IT": "IT research and advisory—Gartner consulting for enterprise software strategy",
  "ITW": "Diversified manufacturer—tools, fasteners, automotive, food equipment",
  "IVZ": "Asset management—mutual funds, ETFs, wealth management globally",
  "J": "Engineering and construction services—infrastructure, industrial projects",
  "JBHT": "Trucking and logistics—freight transportation across North America",
  "JBL": "Electronics manufacturing—printed circuit boards, enclosures, outsourcing",
  "JCI": "Building systems—HVAC, security, fire control for commercial real estate",
  "JKHY": "Fintech for regional banks—core banking, payment processing, cybersecurity",
  "JNJ": "Pharmaceuticals, medical devices, consumer health—diversified healthcare",
  "JPM": "Largest US bank by assets—investment banking, trading, consumer loans",
  "KDP": "Coffee pods (Keurig), Dr Pepper soda—beverage conglomerate",
  "KER.PA": "Groupe de luxe français — Gucci, Saint Laurent, Bottega Veneta, Balenciaga",
  "KEY": "Regional bank—consumer banking, commercial loans across Midwest",
  "KEYS": "Electronic measurement equipment—oscilloscopes, spectrum analyzers for engineers",
  "KHC": "Packaged foods—Kraft, Heinz, Philadelphia cheese, Ore-Ida potatoes",
  "KIM": "Shopping center REIT—owns strip malls and neighborhood retail properties",
  "KKR": "Private equity powerhouse—buyouts, growth equity, infrastructure, real assets",
  "KLAC": "Semiconductor manufacturing equipment—inspection and process control tools",
  "KMB": "Personal care—Kleenex, Huggies, Kotex, Scott tissue brands",
  "KMI": "Energy pipelines and terminals—natural gas and crude oil transport infrastructure",
  "KO": "Beverage conglomerate—Coca-Cola, Sprite, Dasani, Minute Maid juice",
  "KR": "Grocery chain—supermarkets and fuel stations across western United States",
  "KVUE": "Consumer health and personal care—spinoff from J&J, over-the-counter products",
  "L": "Diversified holding company—insurance, oil, hotels, boardgame properties",
  "LDOS": "Defense and intelligence contractor—cyber, IT services for US government",
  "LEN": "Residential home builder—new construction for single-family homes nationwide",
  "LGEN.L": "UK insurance & investment management group, major pension provider",
  "LH": "Lab testing and diagnostics—blood tests, drug screening for patients",
  "LHX": "Aerospace and defense electronics—missiles, military communications systems",
  "LII": "HVAC and refrigeration equipment—heating, cooling systems for buildings",
  "LIN": "Industrial gases (oxygen, nitrogen) and engineering solutions for manufacturing",
  "LLOY.L": "UK's largest retail bank, mortgage lender & insurer",
  "LLY": "Pharmaceutical giant—Ozempic, insulin, immunology, oncology drugs",
  "LMT": "Defense contractor—F-16 fighters, missiles, cybersecurity, rotorcraft",
  "LNT": "Utility company—electric and gas power distribution in Wisconsin, Minnesota",
  "LOW": "Home improvement retail—Lowe's stores, tools, materials nationwide",
  "LR.PA": "Leader mondial des infrastructures électriques & numériques du bâtiment",
  "LRCX": "Semiconductor equipment—chip manufacturing etching and deposition tools",
  "LULU": "Yoga and athletic apparel—premium leggings and sportswear for women",
  "LUV": "Budget airline—low-cost carrier, point-to-point flights across America",
  "LVS": "Casino and hotel operator—luxury resorts in Las Vegas and Macao",
  "LW": "Frozen potato products—french fries, hash browns for food service",
  "LYB": "Petrochemicals and refining—plastics, solvents, fuels from crude oil",
  "LYFT": "Ride-sharing service—app-based car rides competing with Uber",
  "LYV": "Live entertainment—concerts, festivals, sports events promotion globally",
  "MA": "Credit card payment processor—Mastercard brand cards, payment networks",
  "MAA": "Apartment REIT—owns multifamily residential properties across US states",
  "MAR": "Hotel franchiser—Marriott, Ritz-Carlton, Sheraton brands worldwide",
  "MAS": "Building products—cabinets, hardware, installation services for construction",
  "MBG.DE": "German luxury automaker, trucks & vans, EV transition",
  "MC.PA": "Premier groupe mondial de luxe — Louis Vuitton, Dior, Moët, Hennessy, Tiffany",
  "MCD": "Fast food chain—McDonald's restaurants, burgers, fries globally ubiquitous",
  "MCHP": "Microcontroller and semiconductor chips—embedded systems, IoT devices",
  "MCK": "Pharmaceutical distributor—delivers drugs to pharmacies and hospitals",
  "MCO": "Credit rating agency—Moody's ratings for bonds, securities, companies",
  "MDLZ": "Snack foods—Oreo, Trident, Cadbury, Halls across over 150 countries",
  "MDT": "Medical devices—pacemakers, insulin pumps, surgical robotics, diagnostics",
  "MET": "Life insurance and annuities—financial protection and retirement products",
  "META": "Social media and metaverse—Facebook, Instagram, WhatsApp platforms",
  "MGM": "Casino and resort operator—Bellagio, Mandalay, properties in Las Vegas",
  "MKC": "Spice and seasoning manufacturer—McCormick brand, vanilla, pepper globally",
  "ML.PA": "Leader mondial des pneumatiques, aussi guide gastronomique & cartes",
  "MLM": "Construction aggregates and building materials—limestone, asphalt supplier",
  "MMC": "Global insurance broker and risk consultant — manages claims and employee benefits",
  "MMM": "Diversified industrial manufacturer — Post-it, scotch tape, safety, healthcare products",
  "MNDI.L": "South African-British packaging & paper group, sustainable packaging",
  "MNG.L": "British investment & savings group, ex-Prudential UK, asset management",
  "MNST": "Energy drink maker — Monster caffeine-laden beverages targeting gamers and athletes",
  "MO": "Tobacco giant — Marlboro cigarettes, reduced-risk products, shrinking US market",
  "MOH": "Medicaid-focused health insurer — manages government health coverage for lower-income populations",
  "MOS": "Fertilizer and chemicals producer — potash and phosphate for global agriculture",
  "MPC": "Refinery operator and fuel distributor — turns crude oil into gasoline and diesel",
  "MPWR": "Power semiconductor design firm — analog chips for industrial and computing applications",
  "MRK": "Major pharmaceutical company — cancer, vaccines, diabetes drugs plus research pipeline",
  "MRK.DE": "German pharma & life science group (not US Merck), lab equipment & materials",
  "MRNA": "COVID vaccine leader, now mRNA platform — infectious disease and cancer candidates in pipeline",
  "MRSH": "Global consulting and risk firm — insurance broking, HR advisory, actuarial services",
  "MS": "Global investment bank and wealth manager — trading, M&A, advisory for institutions",
  "MSCI": "Index and analytics provider — tracks markets, manages ESG ratings and research",
  "MSFT": "Cloud and software giant — Azure, Office 365, gaming (Xbox), AI ambitions",
  "MSI": "Security and communications equipment — radios, cameras, software for public safety",
  "MT.AS": "Premier producteur mondial d'acier, Luxembourg, mines & sidérurgie",
  "MTB": "Regional bank — serves Northeast and Mid-Atlantic, commercial and retail banking",
  "MTCH": "Dating app ecosystem — Tinder, Hinge, Match, Plenty of Fish monetized via subscriptions",
  "MTD": "Laboratory instruments — balances, titrators, thermal analysis for pharmaceuticals and chemicals",
  "MTX.DE": "German aircraft engine manufacturer, maintenance & repair (MRO)",
  "MU": "Memory chip manufacturer — DRAM and NAND flash for PCs, servers, data centers",
  "MUV2.DE": "World's largest reinsurer, also primary insurance (ERGO)",
  "NCLH": "Cruise line operator — ships, leisure travel, competing with Carnival and Royal Caribbean",
  "NDAQ": "Stock exchange operator — Nasdaq listing, trading, technology services for markets",
  "NDSN": "Industrial adhesives and automation — coating systems, fluid dispensing, industrial components",
  "NEE": "Renewable energy giant — NextEra, nuclear, solar, wind across US and globally",
  "NEM": "Gold mining leader — operations globally, hedging inflation and currency risk",
  "NET": "Cloud security and performance — DDoS protection, WAF, CDN for website protection",
  "NFLX": "Streaming video platform — original content, global subscriber base, ad-supported tier",
  "NG.L": "UK & US electricity/gas transmission grid operator, regulated utility",
  "NG=F": "Henry Hub natural gas futures, US gas benchmark",
  "NI": "Gas utility operator — natural gas distribution, heating for Midwest and Mid-South",
  "NKE": "Athletic apparel and footwear giant — sneakers, apparel, direct-to-consumer push",
  "NOC": "Defense contractor — missiles, satellites, sensors for US military and space programs",
  "NOW": "Cloud software-as-a-service — workflow automation, IT service management for enterprises",
  "NRG": "Independent power producer — natural gas plants, renewable energy, Texas operations",
  "NSC": "Railroad operator — freight rail network spanning Eastern US, coal and intermodal",
  "NTAP": "Storage software and hardware — data management, cloud integration for enterprises",
  "NTRS": "Wealth and asset manager — Northern Trust Bank, custody, investment services",
  "NUE": "Steel manufacturer — electric arc furnaces, structural steel for construction and automotive",
  "NVDA": "GPU and AI chip leader — CUDA platform, data centers, gaming, AI dominance",
  "NVR": "Homebuilder — construction and sales in Northeast, luxury and standard residential",
  "NWG.L": "UK major bank (ex-Royal Bank of Scotland), retail & commercial",
  "NWS": "Media and publishing empire — Fox News, Wall Street Journal, Book Publishing",
  "NWSA": "News Corp Class A shares — Fox News, newspapers, digital media, Rupert Murdoch",
  "NXPI": "Automotive and mobile semiconductors — NFC, automotive processors, Dutch-listed",
  "NZDUSD=X": "New Zealand Dollar vs USD",
  "O": "Dividend aristocrat REIT — commercial real estate, monthly distributions, inflation hedge",
  "ODFL": "LTL freight carrier — less-than-truckload shipping, regional logistics network",
  "OKE": "Midstream energy infrastructure — natural gas pipelines, storage, distribution",
  "OKTA": "Identity and access management — cloud security, single sign-on for enterprises",
  "OMC": "Advertising and marketing — Omnicom Group, creative agencies, digital marketing",
  "ON": "Analog and power semiconductors — sensing, power management, automotive solutions",
  "OR.PA": "Numéro un mondial des cosmétiques, 36 marques internationales",
  "ORA.PA": "Premier opérateur télécom français, aussi présent en Afrique & Europe",
  "ORCL": "Enterprise software giant — databases, cloud computing, ERP, AI infrastructure",
  "ORLY": "Auto parts retailer — O'Reilly stores, DIY and professional mechanics supplies",
  "OTIS": "Elevator and escalator manufacturer — Otis brand, maintenance and modernization services",
  "OXY": "Oil and gas E&P producer — upstream exploration, Middle East and US operations",
  "P911.DE": "German luxury sports car maker (911, Cayenne, Taycan), VW subsidiary",
  "PAH3.DE": "Holding company of Porsche/Piëch families, controls Volkswagen Group",
  "PANW": "Cybersecurity platform company — firewalls, cloud security, zero-trust architecture",
  "PAYC": "Cloud payroll and HR software — Paycom, SMB payroll processing and automation",
  "PAYX": "Payroll processing and HR services — Paychex, outsourced payroll and benefits",
  "PCAR": "Truck manufacturer — Paccar brand, medium-duty commercial vehicles, global sales",
  "PCG": "California utility company — Pacific Gas and Electric, electricity and natural gas",
  "PEG": "New Jersey and New York utility — Public Service Enterprise Group, electricity and gas",
  "PEP": "Global beverage and snacks giant — Pepsi, Frito-Lay, Tropicana, Gatorade",
  "PFE": "Pharmaceutical giant — vaccines, oncology, primary care, Pfizer-BioNTech partnership",
  "PFG": "Financial services and insurance — Principal Financial, retirement and insurance products",
  "PG": "Consumer goods powerhouse — Tide, Gillette, Pampers, Olay, Crest, Oral-B",
  "PGR": "Insurance company — Progressive, auto insurance, digital-first claims and underwriting",
  "PH": "Industrial machinery — Parker-Hannifin, hydraulics, pneumatics, motion control systems",
  "PHM": "Homebuilder — Pultegroup, mass-market residential construction and master-planned communities",
  "PKG": "Corrugated packaging manufacturer — cardboard boxes, recycled containerboard producer",
  "PL=F": "Platinum futures, industrial and precious metal",
  "PLD": "Logistics REIT — warehouses and distribution centers, e-commerce real estate",
  "PLTR": "Data analytics software — Palantir, government contracting, enterprise AI platforms",
  "PM": "Cigarette manufacturer — Philip Morris, Marlboro international, heated tobacco products",
  "PNC": "Regional banking powerhouse — Pittsburgh-based, commercial and retail banking",
  "PNR": "Industrial equipment manufacturer — Pentair pumps, filtration, water management",
  "PNW": "Arizona electric utility — Pinnacle West Capital, APS subsidiary, Southwest power",
  "PODD": "Medical device maker — Insulet, insulin pump systems, wearable diabetes management",
  "POOL": "Swimming pool supplies distributor — Pool Corp, equipment and chemicals nationwide",
  "PPG": "Paints and coatings manufacturer — industrial, aerospace, automotive, architectural",
  "PPL": "Utility company — PPL Electric, Pennsylvania-Kentucky-Indiana power transmission",
  "PRU": "Life insurance and annuities — Prudential Financial, retirement income, protection",
  "PRU.L": "British insurer focused on Asia & Africa, life insurance & asset management",
  "PSA": "Self-storage REIT — Public Storage, mini storage facilities across US and Europe",
  "PSKY": "Entertainment conglomerate — Paramount Skydance, streaming, films, CBS, Showtime",
  "PSON.L": "British education publisher, world's largest learning company, textbooks & digital",
  "PSX": "Refinery and midstream operator — Phillips 66, fuel distribution and logistics",
  "PTC": "Industrial software — PLM, IoT, augmented reality for manufacturing and field service",
  "PUB.PA": "Troisième groupe mondial de publicité & communication (Saatchi, Leo Burnett)",
  "PWR": "Energy infrastructure services — Quanta Services, power grids, fiber optics, renewable",
  "PXD": "Oil exploration and production — Pioneer Natural Resources, Permian Basin legacy",
  "PYPL": "Digital payments platform — PayPal, Venmo, Braintree, cross-border money transfers",
  "Q": "Electronics testing equipment — Qnity Electronics, semiconductor and component testing",
  "QCOM": "Mobile and RF semiconductors — Qualcomm, ARM licenses, 5G modem chips",
  "QGEN.DE": "Dutch-German biotech, molecular diagnostics & sample preparation tech",
  "RCL": "Cruise line operator — Royal Caribbean, Icon Class ships, Caribbean and Mediterranean",
  "REG": "Shopping center REIT — Regency Centers, neighborhood and community retail",
  "REGN": "Biotech pharmaceutical — Regeneron, monoclonal antibodies, immunology pipeline",
  "REL.L": "British-Dutch data analytics & publishing — Elsevier, LexisNexis",
  "RF": "Regional bank — Regions Financial, Southeast banking, commercial and consumer",
  "RHM.DE": "German defense & automotive supplier, tanks (Leopard), ammunition, military vehicles",
  "RI.PA": "Numéro deux mondial des spiritueux — Absolut, Jameson, Ricard, Chivas",
  "RIO.L": "Anglo-Australian mining giant, iron ore, aluminium, copper, lithium",
  "RJF": "Investment bank and broker — Raymond James, wealth management, capital markets",
  "RKT.L": "British consumer health & hygiene — Dettol, Lysol, Durex, Nurofen, Enfamil",
  "RL": "Luxury fashion house — Ralph Lauren, premium apparel, accessories, home products",
  "RMD": "Medical device company — ResMed, respiratory and cloud-connected health devices",
  "RMS.PA": "Maison de luxe française, maroquinerie (Birkin), soie, parfums, artisanat",
  "RNO.PA": "Constructeur automobile français, alliance avec Nissan, virage électrique",
  "ROK": "Industrial automation — Rockwell Automation, factory control systems, software",
  "ROL": "Pest control services — Rollins Inc, professional extermination and fumigation",
  "ROP": "Diversified industrial conglomerate — Roper, Xylem, water and industrial software",
  "ROST": "Off-price retailer — Ross Stores, discounted brand-name apparel and home goods",
  "RR.L": "British aerospace & defense — aircraft engines, nuclear submarines, power systems",
  "RSG": "Waste management — Republic Services, trash collection and recycling services",
  "RTX": "Aerospace and defense — Raytheon Technologies, Pratt & Whitney, Collins Aerospace",
  "RVTY": "Life sciences tools — Revvity, laboratory equipment, diagnostics, imaging products",
  "RWE.DE": "Major German utility, largest wind power producer in Europe, energy transition",
  "SAF.PA": "Motoriste aéronautique (LEAP avec GE), équipements avions, défense",
  "SAIC": "Defense contractor — Science Applications Int'l, government IT and engineering services",
  "SAN.PA": "Géant pharmaceutique français, vaccins (Pasteur), immunologie (Dupixent)",
  "SAP.DE": "Europe's largest software company, enterprise ERP & cloud business solutions",
  "SBAC": "Wireless tower REIT — SBA Communications, cell towers, colocation infrastructure",
  "SBUX": "Coffee chain and retailer — Starbucks, 16,000 locations, premium beverages",
  "SCHW": "Brokerage and investment services — Charles Schwab, retail investing, robo-advisor",
  "SDR.L": "British asset management firm, one of UK's oldest fund managers",
  "SGE.L": "British business software company, accounting & payroll for SMEs",
  "SGO.PA": "Leader mondial des matériaux de construction, isolation, vitrage",
  "SHEL.L": "British-Dutch oil & gas major, one of world's largest energy companies",
  "SHL.DE": "German medical technology — imaging (MRI, CT), lab diagnostics, Varian oncology",
  "SHOP": "E-commerce platform — Shopify, merchant platform, point-of-sale systems",
  "SHW": "Paint and coatings — Sherwin-Williams, architectural, industrial, DIY retail",
  "SI=F": "Silver futures, dual industrial and precious metal",
  "SIE.DE": "German industrial conglomerate — automation, trains, smart infrastructure",
  "SJM": "Food manufacturer — J.M. Smucker, jams, peanut butter, pet food brands",
  "SKG.L": "Irish corrugated packaging leader, now merged with WestRock",
  "SLB": "Oilfield services giant — Schlumberger, seismic, drilling, production services",
  "SMCI": "Server hardware maker powering AI data centers globally",
  "SNA": "Snap-on makes professional tools for technicians and engineers",
  "SNAP": "Snapchat owner, image-focused social platform with advertising",
  "SNDK": "SanDisk makes flash memory and storage devices for consumers",
  "SNOW": "Snowflake provides cloud data warehouse platform for enterprise",
  "SNPS": "Synopsys creates semiconductor design software and tools",
  "SO": "Southern Company operates electric utility serving Southeast US",
  "SOL-USD": "High-speed blockchain, DeFi and NFT ecosystem",
  "SOLV": "Solventum provides healthcare solutions and infection prevention products",
  "SPG": "Simon Property Group owns and operates shopping malls nationwide",
  "SPGI": "S&P Global provides credit ratings, index data, analytics",
  "SQ": "Block operates Square payments and Cash App platforms",
  "SRE": "Sempra Energy transmits electricity and gas to California",
  "SRT3.DE": "German bioprocess equipment & lab instruments, pharma manufacturing tools",
  "SSE.L": "Scottish energy company, largest UK renewable electricity generator, wind farms",
  "STAN.L": "British bank focused on Asia, Africa & Middle East, trade finance",
  "STE": "Steris sterilizes medical equipment and supplies for hospitals",
  "STLAM.MI": "Groupe automobile (fusion PSA+FCA) — Peugeot, Citroën, Fiat, Jeep, RAM",
  "STLD": "Steel Dynamics produces flat-rolled and structural steel products",
  "STMPA.PA": "Fabricant européen de semi-conducteurs, capteurs, puces auto & industriel",
  "STT": "State Street provides financial data and custody services",
  "STX": "Seagate manufactures hard drives and storage solutions",
  "STZ": "Constellation Brands brews Corona beer and spirits globally",
  "SU.PA": "Leader mondial de la gestion de l'énergie & automatisation industrielle",
  "SVNL.L": "British outsourcing & government services — prisons, transport, defense",
  "SVT.L": "UK water utility, serves central England & Wales",
  "SW": "Smurfit Westrock produces corrugated packaging and paper products",
  "SW.PA": "Leader mondial de la restauration collective & services aux entreprises",
  "SWK": "Stanley Black & Decker makes tools, locks, home equipment",
  "SWKS": "Skyworks Solutions designs semiconductor chips for mobile devices",
  "SY1.DE": "German flavors & fragrances producer, food/cosmetics ingredients",
  "SYF": "Synchrony Financial provides credit cards and consumer financing",
  "SYK": "Stryker manufactures orthopedic and medical devices for hospitals",
  "SYY": "Sysco distributes food and beverages to restaurants and institutions",
  "T": "AT&T operates telecommunications networks across United States",
  "TAP": "Molson Coors brews and distributes beer nationwide and globally",
  "TDG": "TransDigm Group supplies aircraft components and aerospace systems",
  "TDY": "Teledyne Technologies designs sensors and instruments for aerospace",
  "TECH": "Bio-Techne manufactures life science research reagents and instruments",
  "TEL": "TE Connectivity makes connectors and sensors for electronics",
  "TEP.PA": "Leader mondial des centres d'appels & services clients externalisés",
  "TER": "Teradyne manufactures semiconductor test equipment for chip makers",
  "TFC": "Truist Financial provides banking and wealth management services",
  "TGT": "Target operates discount retail stores across United States",
  "TJX": "TJX Companies runs off-price stores including TJ Maxx and Marshalls",
  "TKO": "TKO Group Holdings owns UFC and WWE sports entertainment",
  "TMO": "Thermo Fisher Scientific provides laboratory equipment and chemicals",
  "TMUS": "T-Mobile US operates wireless network and mobile services",
  "TOL": "Toll Brothers builds luxury residential homes in major markets",
  "TPL": "Texas Pacific Land owns oil and gas properties in Texas",
  "TPR": "Tapestry designs luxury handbags and fashion accessories",
  "TRGP": "Targa Resources processes crude oil and natural gas",
  "TRMB": "Trimble provides GPS positioning and construction software solutions",
  "TROW": "T. Rowe Price manages mutual funds and investment services",
  "TRV": "Travelers Companies provides property and casualty insurance",
  "TSCO": "Tractor Supply sells farm equipment and rural supplies",
  "TSCO.L": "UK's largest supermarket chain, also banking & mobile services",
  "TSLA": "Tesla manufactures electric vehicles and energy storage systems",
  "TSN": "Tyson Foods processes and sells poultry, beef, pork globally",
  "TT": "Trane Technologies makes HVAC and refrigeration systems",
  "TTD": "Trade Desk provides programmatic advertising platform for marketers",
  "TTE.PA": "Major pétro-gazière française, aussi renouvelables & électricité",
  "TTWO": "Take-Two Interactive develops video games like GTA and NBA 2K",
  "TXN": "Texas Instruments manufactures analog and embedded semiconductors",
  "TXT": "Textron makes helicopters, aircraft, and defense equipment",
  "TYL": "Tyler Technologies provides software for local governments",
  "UAL": "United Airlines operates flights across US and international routes",
  "UBER": "Uber provides ride-sharing and food delivery via app",
  "UDR": "UDR operates residential apartment communities across United States",
  "UHS": "Universal Health Services operates hospitals and behavioral facilities",
  "ULTA": "Ulta Beauty operates cosmetics and beauty supply retail stores",
  "ULVR.L": "British-Dutch consumer goods giant — Dove, Ben & Jerry's, Knorr",
  "UNH": "UnitedHealth Group provides health insurance and services",
  "UNP": "Union Pacific operates freight railroad across western United States",
  "UPS": "United Parcel Service delivers packages and parcels worldwide",
  "URI": "United Rentals leases heavy construction and mobile equipment",
  "URW.AS": "Premier opérateur européen de centres commerciaux premium",
  "USB": "US Bancorp provides banking and wealth management services",
  "USDCAD=X": "US Dollar vs Canadian Dollar, oil-linked pair",
  "USDCHF=X": "US Dollar vs Swiss Franc, safe-haven pair",
  "USDJPY=X": "US Dollar vs Japanese Yen, carry trade barometer",
  "UU.L": "UK's largest listed water company, serves North West England",
  "V": "Visa processes credit card payments globally for merchants",
  "VICI": "Vici Properties owns casino properties in Las Vegas and beyond",
  "VIE.PA": "Leader mondial du traitement de l'eau, déchets & énergie",
  "VIV.PA": "Groupe média français — Canal+, Havas, Gameloft, Editis",
  "VLO": "Valero Energy refines crude oil into gasoline and fuels",
  "VLTO": "Veralto provides water quality and environmental monitoring equipment",
  "VMC": "Vulcan Materials Company extracts and sells aggregates and stone",
  "VNA.DE": "Europe's largest residential real estate group, ~550k apartments in Germany",
  "VOD.L": "British telecom, one of world's largest mobile operators, Europe & Africa",
  "VOW3.DE": "World's largest automaker by revenue — VW, Audi, Porsche, Lamborghini, Skoda",
  "VRSK": "Verisk Analytics provides risk assessment and data analytics",
  "VRSN": "Verisign operates the .com and .net domain registry",
  "VRTX": "Vertex Pharmaceuticals develops cystic fibrosis and genetic disease drugs",
  "VST": "Vistra Corp generates and sells electric power in Texas",
  "VTR": "Ventas owns senior housing and healthcare properties",
  "VTRS": "Viatris manufactures generic and branded pharmaceuticals",
  "VZ": "Verizon Communications operates wireless and broadband networks",
  "WAB": "Wabtec manufactures locomotives and transit equipment",
  "WAT": "Waters Corporation makes laboratory analysis instruments and equipment",
  "WBA": "Walgreens operates pharmacy and retail drugstores nationwide",
  "WBD": "Warner Bros Discovery produces and distributes film and television",
  "WDAY": "Workday provides cloud human resources and finance software",
  "WDC": "Western Digital manufactures data storage devices and controllers",
  "WEC": "WEC Energy Group supplies electricity and natural gas to states",
  "WEIR.L": "Scottish engineering, mining equipment & industrial pumps",
  "WELL": "Welltower owns senior housing and healthcare real estate",
  "WFC": "Wells Fargo provides banking and financial services nationwide",
  "WIZZ.L": "Hungarian ultra-low-cost airline, Eastern Europe & Middle East routes",
  "WLN.PA": "Leader européen des paiements électroniques & services transactionnels",
  "WM": "Waste Management collects and processes waste management services",
  "WMB": "Williams Companies operates natural gas pipeline infrastructure",
  "WMT": "Walmart operates discount retail stores across United States",
  "WPP.L": "World's largest advertising & PR holding company (Ogilvy, GroupM)",
  "WRB": "W. R. Berkley provides specialty insurance products",
  "WSM": "Williams-Sonoma sells home furnishings and kitchenware retail",
  "WST": "West Pharmaceutical manufactures injectable drug delivery systems",
  "WTW": "Willis Towers Watson provides insurance and risk management services",
  "WY": "Weyerhaeuser owns and manages timber and forest properties",
  "WYNN": "Wynn Resorts operates luxury casino and resort properties",
  "X": "United States Steel manufactures flat-rolled and tubular steel",
  "XEL": "Xcel Energy provides electricity and natural gas to western states",
  "XLE": "SPDR energy sector ETF tracking S&P 500 oil and gas stocks",
  "XLF": "SPDR financial sector ETF tracking S&P 500 banks and insurers",
  "XLK": "SPDR technology sector ETF tracking S&P 500 tech stocks",
  "XOM": "Exxon Mobil explores and produces crude oil and natural gas",
  "XRX.L": "British industrial inkjet printhead manufacturer, niche printing technology",
  "XYL": "Xylem manufactures water and wastewater equipment solutions",
  "XYZ": "Fintech company (formerly Square) — Cash App, payments, Bitcoin services",
  "YUM": "Yum! Brands franchises KFC, Taco Bell, and Pizza Hut globally",
  "ZAL.DE": "Europe's largest online fashion platform, German e-commerce",
  "ZBH": "Zimmer Biomet manufactures orthopedic and surgical implants",
  "ZBRA": "Zebra Technologies provides barcode and RFID printing solutions",
  "ZS": "Zscaler provides cloud-based cybersecurity and network security",
  "ZTS": "Zoetis manufactures animal health pharmaceuticals and vaccines",
  "ZW=F": "CBOT wheat futures, global grain benchmark",
};

/** Resolve a Yahoo symbol to a human-readable name. */
export function assetName(symbol: string): string {
  return ASSET_NAMES[symbol] ?? symbol.replace(/^[^]/, '').replace(/[=].*$/, '');
}

/** Get editorial aliases for a symbol (empty array if none). */
export function assetAliases(symbol: string): string[] {
  return ASSET_ALIASES[symbol] ?? [];
}

/** Get one-line description for a symbol (undefined if none). */
export function assetDescription(symbol: string): string | undefined {
  return ASSET_DESCRIPTIONS[symbol];
}
