export interface Candle {
  t: number;
  date: string;
  o: number;
  h: number;
  l: number;
  c: number;
  v: number;
}

export type AspectMode = "landscape" | "portrait";

export type EpisodeType = "daily_recap" | "chart_analysis";
export type Language = "fr" | "en";

export type SectionType =
  | "hook" | "title_card" | "thread"
  | "segment" | "closing"
  // legacy (backward compatibility)
  | "intro" | "market_overview" | "deep_dive" | "news" | "predictions" | "outro"
  | "synthesis" | "watchlist" | "recap_cta" | "previously_on" | "suivi";

export interface VisualCue {
  type: "highlight_asset" | "show_chart" | "show_level" | "direction_arrow" | "flash" | "transition"
    | "sector_heatmap" | "macro_stat" | "comparison";
  asset?: string;
  value?: number;
  label?: string;
  direction?: "up" | "down";
  confidence?: "high" | "medium" | "low";
}

export interface ScriptSection {
  id: string;
  type: SectionType;
  title: string;
  narration: string;
  durationSec: number;
  visualCues: VisualCue[];
  data?: Record<string, unknown>;
  depth?: "flash" | "focus" | "deep" | "panorama";
  topic?: string;
  assets?: string[];
  /** Concept visuel éditorial (Opus C3) — scène narrative pour le directeur artistique C7 */
  editorialVisual?: string;
  /** Phrase de transition du hibou avant ce segment */
  owlTransition?: string;
}

export interface EpisodeDirection {
  arc: Array<{
    segmentId: string;
    tensionLevel: number;
    role: 'hook' | 'montee' | 'pic' | 'respiration' | 'rebond' | 'resolution' | 'closing';
  }>;
  transitions: Array<{
    fromSegmentId: string;
    toSegmentId: string;
    type: 'cut' | 'fade' | 'wipe' | 'zoom_out' | 'slide';
    durationMs: number;
    soundEffect?: 'silence' | 'none' | 'swoosh' | 'typing' | 'sting' | 'bell' | 'stamp' | 'pen' | 'ticker' | 'clock' | 'unfold' | 'close' | 'cabinet';
    vocalShift?: string;
  }>;
  chartTimings: Array<{
    chartInstruction: {
      type: string;
      asset: string;
      value?: number;
      label?: string;
      timeframe?: string;
    };
    showAtSec: number;
    hideAtSec: number;
  }>;
  moodMusic: 'tension_geopolitique' | 'risk_off_calme' | 'bullish_momentum' | 'neutre_analytique' | 'incertitude';
  thumbnailMoment: {
    segmentId: string;
    reason: string;
    keyFigure?: string;
    emotionalTone: string;
  };
}

export interface EpisodeScript {
  episodeNumber: number;
  date: string;
  type: EpisodeType;
  lang: Language;
  title: string;
  description: string;
  sections: ScriptSection[];
  totalDurationSec: number;
  threadSummary: string;
  segmentCount: number;
  coverageTopics: string[];
  mechanismsExplained?: string[];
  direction?: EpisodeDirection;
  /** Cold-open punch card — 3 short fragments shown before the owl intro
   *  to hook viewers in the first 3 seconds. Generated by C3 Opus, with a
   *  rule-based fallback derived from the hook narration if absent. */
  coldOpenPunch?: { fragments: string[] };
  /** Owl intro speech (welcome + date + disclaimer) */
  owlIntro?: string;
  /** Owl closing speech (recap + subscribe + goodbye) */
  owlClosing?: string;
  /** YouTube SEO metadata (P10 C10 output) */
  seo?: EpisodeSEO;
}

export interface EpisodeSEOChapter {
  time: string;
  label: string;
}

export interface EpisodeSEO {
  title: string;
  description: string;
  chapters: EpisodeSEOChapter[];
  tags: string[];
  hashtags: string[];
  /**
   * Premier commentaire posté automatiquement après upload (engagement booster).
   * Court (200-400 chars), éditorial, question ouverte aux viewers, CTA abonnement soft.
   * Pas de liens (filtré spam). À épingler manuellement dans Studio (pas d'API pour pinning).
   */
  pinnedComment?: string;
}

export interface MultiTimeframeAnalysis {
  weekly10y: {
    trend: "bull" | "bear" | "range";
    distanceFromATH: number;    // % from ATH (negative = below, e.g. -5.2)
    distanceFromATL: number;    // % above ATL (positive, e.g. +340)
    majorSupport: number;
    majorResistance: number;
    ema52w: number;
  };
  daily3y: {
    trend: "bull" | "bear" | "range";
    sma200: number;
    sma50: number;
    rsi14: number;
    aboveSma200: boolean;
    goldenCross: boolean;       // SMA50 > SMA200
  };
  daily1y: {
    trend: "bull" | "bear" | "range";
    high52w: number;
    low52w: number;
    volatility20d: number;      // annualized %
    volumeVsAvg: number;        // ratio vs 20d avg
    recentBreakout: boolean;    // price within 1% of 52w high
  };
}

export interface AssetSnapshot {
  symbol: string;
  name: string;
  /** Live price at fetch time (intraday if market is open, last close otherwise). */
  price: number;
  change: number;
  /**
   * Variation de la SÉANCE J-1 (la vraie bougie d'hier, close J-1 vs close J-2).
   * Calculé depuis les daily candles dans market-snapshot.ts Phase 2.
   * Fallback sur la variation intraday si dailyCandles indisponibles.
   */
  changePct: number;
  candles: Candle[];
  high24h: number;
  low24h: number;
  // ── Session J-1 fields (computed from dailyCandles) ────────
  /** Close de la séance J-1 (la "clôture d'hier"). */
  sessionClose?: number;
  /** Close de la séance J-2 (référence pour changePct). */
  prevSessionClose?: number;
  /** High de la séance J-1 (pour "a touché X en séance"). */
  sessionHigh?: number;
  /** Low de la séance J-1. */
  sessionLow?: number;
  /** Amplitude absolue (sessionHigh - sessionLow). */
  sessionRange?: number;
  /** Amplitude relative en % (sessionRange / prevSessionClose * 100). */
  sessionRangePct?: number;
  /** Date de la séance J-1 (YYYY-MM-DD) pour traçabilité. */
  sessionDate?: string;
  /**
   * Variation intraday depuis la clôture J-1 : (price - sessionClose) / sessionClose.
   * Utile pour coupler avec les news `post_session` / events `pub_morning_*`.
   */
  changePctNow?: number;
  /**
   * True si le marché de cet asset était fermé sur la narrative date (holiday).
   * L'asset garde sa dernière session valide (avant fermeture). Détection :
   * inférence sur sessionDate < narrativeDate, lag ≤ 14j (au-delà = drop).
   *
   * Effets dans le pipeline :
   * - dramaScore est forcé à 0 (ne devient pas un mover)
   * - Editorial score le dépriorise
   * - P3 prompt mentionne sa fermeture pour que le LLM en parle brièvement
   */
  marketClosed?: boolean;
  /** Jours calendaires entre la dernière session et la narrative date (1-14). */
  daysSinceLastSession?: number;
  // Enriched fields (populated by computeTechnicals)
  dailyCandles?: Candle[];
  technicals?: TechnicalIndicators;
  // Multi-timeframe analysis (weekly 10y + daily 3y)
  multiTF?: MultiTimeframeAnalysis;
  // Multi-timeframe performance (computed from dailyCandles)
  perf?: {
    // ── ROLLING (fenêtres glissantes, pour "sur la semaine/mois/année écoulée") ──
    /** 5 trading days — rolling 1 semaine */
    week?: number;
    /** ~22 trading days — rolling 1 mois */
    month?: number;
    /** ~66 trading days — rolling 3 mois */
    quarter?: number;
    /** ~252 trading days — rolling 1 an */
    year?: number;
    // ── CALENDAIRE (to-date, pour "depuis le 1er janvier/du mois") ──
    /** Week-to-date — depuis la clôture du dimanche (ou vendredi avant) */
    wtd?: number;
    /** Month-to-date — depuis la dernière clôture du mois précédent */
    mtd?: number;
    /** Quarter-to-date — depuis la dernière clôture du trimestre précédent */
    qtd?: number;
    /** Year-to-date — depuis la dernière clôture de l'année précédente */
    ytd?: number;
    // ── EXTRÊMES HISTORIQUES ──
    /** Drawdown depuis plus haut historique (dans la fenêtre candles) */
    fromATH?: number;
    /** Rebond depuis plus bas 52 semaines */
    from52wLow?: number;
  };
  /** Asset class for peer comparison (derived from symbol). Same group = comparable in narrative. */
  group?: AssetGroup;
}

/** Asset grouping for peer comparison (e.g. S&P vs CAC = indices comparables). */
export type AssetGroup =
  | 'US_INDEX' | 'EU_INDEX' | 'ASIA_INDEX'
  | 'FX_MAJOR'
  | 'ENERGY' | 'METAL' | 'AGRI'
  | 'CRYPTO'
  | 'BOND_US' | 'BOND_EU'
  | 'VOLATILITY'
  | 'STOCK_US' | 'STOCK_FR' | 'STOCK_DE' | 'STOCK_UK' | 'STOCK_JP' | 'STOCK_HK' | 'STOCK_CN'
  | 'ETF_SECTOR'
  | 'OTHER';

export interface TechnicalIndicators {
  sma20: number;
  sma50: number;
  rsi14: number;
  trend: "bullish" | "bearish" | "neutral";
  volumeAnomaly: number; // ratio vs 20d average
  supports: number[];
  resistances: number[];
  high20d: number;
  low20d: number;
  isNear52wHigh: boolean;
  isNear52wLow: boolean;
  dramaScore: number;
}

export interface NewsItem {
  title: string;
  source: string;
  url: string;
  publishedAt: string;
  summary?: string;
  category?: string;
  lang?: "fr" | "en";
}

export interface EconomicEvent {
  name: string;
  date: string;
  time: string;
  currency: string;
  impact: "high" | "medium" | "low";
  forecast?: string;
  previous?: string;
  actual?: string;
}

export interface Prediction {
  asset: string;
  direction: "bullish" | "bearish" | "neutral";
  confidence: "high" | "medium" | "low";
  targetLevel?: number;
  keyLevel?: number;
  reasoning: string;
}

export interface BondYields {
  us10y: number;
  us2y: number;
  spread10y2y: number;
}

export interface MarketSentiment {
  cryptoFearGreed: { value: number; label: string };
  btcDominance: number;
  trendingCoins?: Array<{ name: string; symbol: string; rank: number }>;
}

export interface EarningsEvent {
  symbol: string;
  name?: string;
  date: string;
  epsEstimate?: number;
  epsActual?: number;
  revenueEstimate?: number;
  revenueActual?: number;
  hour: "bmo" | "amc" | "dmh";
  reported?: boolean;
}

export interface EarningsQuarter {
  period: string;             // "2025-09-30"
  quarter: number;            // 1-4
  year: number;
  epsActual?: number;
  epsEstimate?: number;
  surprisePct?: number;       // % beat (+) or miss (-)
}

export interface EarningsDetail {
  lastFourQuarters: EarningsQuarter[];  // most recent first
  currentQtrEpsEstimate?: number;       // from EarningsEvent already fetched
  publishingToday: boolean;
}

export interface StockScreenResult {
  symbol: string;
  name: string;
  index: string;              // "SP500" | "CAC40" | "DAX40" | "FTSE100" | "NIKKEI50" | "HSI30"
  price: number;
  changePct: number;
  volume: number;
  avgVolume: number;
  high52w: number;
  low52w: number;
  reason: string[];           // ["mover_up", "volume_spike", "52w_high"]
  technicals?: TechnicalIndicators;
  earningsDetail?: EarningsDetail;
  /** GICS sector or Finnhub industry (from company-profiles.json) */
  sector?: string;
  /** One-line description for LLM context ("Chinese food delivery platform") */
  description?: string;
}

export interface PolymarketMarket {
  id: string;
  question: string;
  category: string;
  endDate: string;
  probabilities: Record<string, number>;  // { "Yes": 68, "No": 32 } — values in %
  volume24h: number;
  liquidity: number;
}

export interface SectorCluster {
  sector: string;
  movers: Array<{ symbol: string; name: string; changePct: number }>;
  avgChangePct: number;
  direction: "up" | "down";
}

export interface ActiveCausalChain {
  id: string;
  name: string;
  confidence: number;       // 0-1
  confirmedSteps: string[];
  suggestedNarration: string;
  relatedAssets: string[];
}

export interface EventSurprise {
  eventName: string;
  actual: number;
  forecast: number;
  surprisePct: number;
  magnitude: "neutral" | "minor" | "notable" | "major";
  direction: "above" | "below" | "inline";
  relatedAssets: string[];
}

export interface Theme {
  id: string;
  label: { fr: string; en: string };
  editorialScore: number;
  buzzScore: number;
  assets: string[];          // symbols
  events: string[];          // event names
  newsItems: string[];       // article titles
  causalChain?: string[];    // active causal links
  sectorClusters?: SectorCluster[];
  breakdown: {
    amplitude: number;
    breadth: number;
    surprise: number;
    causalDepth: number;
    symbolic: number;
    newsFrequency: number;
    regimeCoherence: number;
  };
}

export interface ThemesDuJour {
  themes: Theme[];
  causalChains: ActiveCausalChain[];
  sectorClusters: SectorCluster[];
  eventSurprises: EventSurprise[];
  marketRegime: string;
}

export interface COTCategoryData {
  netPosition: number;
  long: number;
  short: number;
  pctOfOI: number;          // net as % of open interest
}

export interface COTContractData {
  reportDate: string;        // YYYY-MM-DD (Tuesday snapshot date)
  openInterest: number;
  assetManagers: COTCategoryData;   // TFF: Asset Managers / Disagg: Managed Money
  leveragedFunds: COTCategoryData;  // TFF: Leveraged Funds / Disagg: Swap Dealers
  dealers: COTCategoryData;         // TFF: Dealers / Disagg: Producers
  signals?: {
    netChangeSpeculators: number;   // week-over-week change in speculator net
    percentileRank: number;         // 0-100, current net vs 10-week range
    bias: "extreme_long" | "extreme_short" | "long" | "short" | "neutral";
    flipDetected: boolean;          // sign change in speculator net position
    weeksInDirection: number;       // consecutive weeks same direction
  };
}

export interface COTPositioning {
  reportDate: string;
  contracts: Array<{
    symbol: string;
    name: string;
    reportType: "tff" | "disaggregated";
    current: COTContractData;
    history: COTContractData[];      // previous weeks (oldest last)
  }>;
}

export interface DailySnapshot {
  date: string;
  assets: AssetSnapshot[];
  news: NewsItem[];
  events: EconomicEvent[];
  yesterdayEvents?: EconomicEvent[];
  upcomingEvents?: EconomicEvent[];
  yields?: BondYields;
  /** Historical yield timeseries for SpreadChart rendering (from FRED) */
  yieldsHistory?: {
    us10y: Candle[];
    us2y: Candle[];
    spread10y2y: Candle[];
  };
  sentiment?: MarketSentiment;
  earnings?: EarningsEvent[];
  earningsUpcoming?: EarningsEvent[];  // J+1 to J+21
  stockScreen?: StockScreenResult[];
  polymarket?: PolymarketMarket[];
  cotPositioning?: COTPositioning;
  themesDuJour?: ThemesDuJour;
}

export interface EpisodeManifestEntry {
  episodeNumber: number;
  date: string;
  type: EpisodeType;
  lang: Language;
  title: string;
  filePath: string;
  predictions?: Prediction[];
}

export interface AudioSegment {
  sectionId: string;
  audioPath: string;
  durationSec: number;
  words?: Array<{ word: string; start: number; end: number }>;
}

export interface AudioManifest {
  segments: AudioSegment[];
  totalDurationSec: number;
}

// ── Beat Pipeline Types (Bloc E v2) ─────────────────────

export type ImageEffect =
  | 'ken_burns_in'
  | 'ken_burns_out'
  | 'slow_pan_left'
  | 'slow_pan_right'
  | 'static';

export type BeatTransition =
  | 'cut'
  | 'fade'
  | 'slide_left'
  | 'slide_up'
  | 'wipe'
  | 'cross_dissolve';

export type BeatEmotion =
  | 'tension'
  | 'analyse'
  | 'revelation'
  | 'contexte'
  | 'impact'
  | 'respiration'
  | 'conclusion';

export type OverlayType =
  | 'stat'
  | 'chart'
  | 'chart_zone'
  | 'spread_chart'
  | 'causal_chain'
  | 'comparison'
  | 'headline'
  | 'text_card'
  | 'heatmap'
  | 'scenario_fork'
  | 'gauge'
  | 'ticker_strip'
  | 'countdown_event';

export interface BeatOverlay {
  type: OverlayType;
  data: Record<string, unknown>;
  position: 'center' | 'bottom_third' | 'lower_third' | 'top_right' | 'full';
  enterAnimation: 'pop' | 'slide_up' | 'fade' | 'count_up';
  enterDelayMs: number;
  triggerWord?: string;
}

export interface BeatTiming {
  estimatedDurationSec: number;
  audioDurationSec?: number;
  wordTimestamps?: Array<{
    word: string;
    startMs: number;
    endMs: number;
  }>;
}

export interface Beat {
  id: string;
  segmentId: string;
  startSec: number;
  durationSec: number;
  narrationChunk: string;
  timing: BeatTiming;
  imagePrompt: string;
  imagePath?: string;
  imageReuse?: string;
  imageEffect: ImageEffect;
  overlay?: BeatOverlay;
  transitionOut: BeatTransition;
  emotion: BeatEmotion;
  audioPath?: string;
}

export interface EpisodeVisualIdentity {
  colorTemperature: 'warm' | 'cool' | 'neutral';
  lightingRegister: 'soft_natural' | 'golden_hour' | 'overcast' | 'studio_warm';
  photographicStyle: string;
  forbiddenElements: string[];
}

export interface BeatEpisodeData {
  beats: Beat[];
  visualIdentity: EpisodeVisualIdentity;
  totalBeats: number;
  uniqueImages: number;
  stats: {
    overlayCount: number;
    imageOnlyCount: number;
    avgBeatDurationSec: number;
  };
}
