/**
 * MarketMemory — per-asset technical memory (Bloc D3)
 * One JSON file per asset in data/market-memory/{symbol}.json
 */

export type ZoneEventType = "TOUCH" | "REJET" | "CASSURE" | "PULLBACK_TENU" | "PULLBACK_RATE";

export interface Zone {
  level: number;
  type: "support" | "resistance" | "pivot";
  created: string;           // ISO date
  touches: number;
  last_touch: string;        // ISO date
  last_event_type: ZoneEventType | null;
  cassure_date: string | null;
  cassure_confirmed: boolean | null;  // null = pending, true/false = resolved
  last_behavior: string;     // free-form note from Haiku/Sonnet
}

export interface DailyIndicators {
  date: string;              // ISO date of calculation
  bb_width_pct: number;      // Bollinger Band width as % of price
  bb_width_pct_rank: number; // percentile rank over 90 days (0-100)
  mm20_slope_deg: number;    // SMA20 slope in degrees
  atr14: number;
  atr90: number;
  atr_ratio: number;         // atr14 / atr90
  volume_ratio_20d: number;  // today volume / 20d average
  rsi14: number;
}

export interface ZoneEvent {
  date: string;
  event_type: ZoneEventType;
  detail: string;
}

export interface AssetMarketMemory {
  symbol: string;
  name: string;
  context: {
    regime: "bull" | "bear" | "range";
    regime_since: string;       // ISO date
    impression: string;         // weekly Sonnet summary
    impression_updated: string; // ISO date
  };
  zones: Zone[];                // 3-5 zones max per asset
  indicators_daily: DailyIndicators | null;
  last_events: ZoneEvent[];     // 5 max, FIFO
}

/** Haiku enrichment result for a single asset */
export interface HaikuEnrichmentResult {
  symbol: string;
  zone_updates: Array<{
    level: number;
    last_behavior: string;
    cassure_confirmed?: boolean;
  }>;
  tactical_note: string;
}

/** Weekly brief generated by Sonnet */
export interface MarketWeeklyBrief {
  generated: string;          // ISO datetime
  regime_summary: string;     // 2-3 sentences on overall market
  notable_zones: Array<{
    symbol: string;
    level: number;
    type: string;
    event: string;            // what happened this week
  }>;
  watchlist_next_week: Array<{
    symbol: string;
    reason: string;
  }>;
}

/** List of symbols eligible for MarketMemory (no ETFs, no individual stocks) */
export const MARKET_MEMORY_SYMBOLS: Array<{ symbol: string; name: string; category: string }> = [
  // Indices US (4)
  { symbol: "^GSPC", name: "S&P 500", category: "index" },
  { symbol: "^IXIC", name: "Nasdaq Composite", category: "index" },
  { symbol: "^DJI", name: "Dow Jones", category: "index" },
  { symbol: "^VIX", name: "VIX", category: "index" },
  // Indices EU (4)
  { symbol: "^FCHI", name: "CAC 40", category: "index" },
  { symbol: "^GDAXI", name: "DAX 40", category: "index" },
  { symbol: "^FTSE", name: "FTSE 100", category: "index" },
  { symbol: "^STOXX", name: "STOXX Europe 600", category: "index" },
  // Indices Asia (5)
  { symbol: "^N225", name: "Nikkei 225", category: "index" },
  { symbol: "000001.SS", name: "Shanghai Composite", category: "index" },
  { symbol: "^HSI", name: "Hang Seng", category: "index" },
  { symbol: "^KS11", name: "KOSPI", category: "index" },
  { symbol: "399001.SZ", name: "Shenzhen Component", category: "index" },
  // Forex (11)
  { symbol: "DX-Y.NYB", name: "US Dollar Index", category: "forex" },
  { symbol: "EURUSD=X", name: "EUR/USD", category: "forex" },
  { symbol: "USDJPY=X", name: "USD/JPY", category: "forex" },
  { symbol: "GBPUSD=X", name: "GBP/USD", category: "forex" },
  { symbol: "USDCHF=X", name: "USD/CHF", category: "forex" },
  { symbol: "AUDUSD=X", name: "AUD/USD", category: "forex" },
  { symbol: "USDCAD=X", name: "USD/CAD", category: "forex" },
  { symbol: "NZDUSD=X", name: "NZD/USD", category: "forex" },
  { symbol: "EURGBP=X", name: "EUR/GBP", category: "forex" },
  { symbol: "EURJPY=X", name: "EUR/JPY", category: "forex" },
  { symbol: "GBPJPY=X", name: "GBP/JPY", category: "forex" },
  // Commodities (8)
  { symbol: "GC=F", name: "Gold", category: "commodity" },
  { symbol: "SI=F", name: "Silver", category: "commodity" },
  { symbol: "HG=F", name: "Copper", category: "commodity" },
  { symbol: "CL=F", name: "Crude Oil WTI", category: "commodity" },
  { symbol: "BZ=F", name: "Brent Crude", category: "commodity" },
  { symbol: "NG=F", name: "Natural Gas", category: "commodity" },
  { symbol: "ZW=F", name: "Wheat", category: "commodity" },
  { symbol: "PL=F", name: "Platinum", category: "commodity" },
  // Crypto (3)
  { symbol: "BTC-USD", name: "Bitcoin", category: "crypto" },
  { symbol: "ETH-USD", name: "Ethereum", category: "crypto" },
  { symbol: "SOL-USD", name: "Solana", category: "crypto" },
];
