// ── Chunk Index Types ─────────────────────────────────────
// Types for the knowledge chunk matching system.
// The chunk index (index.json) is generated by the chunking script
// and consumed by knowledge-matcher.ts at runtime.

export interface ChunkConditions {
  flags: string[];              // MaterialityFlag names
  actors: string[];             // Political actor IDs
  regimes: string[];            // Market regime names
  vix_above: number | null;
  any_symbol_move: boolean;
  seasonality_months: number[];
}

export interface ChunkMeta {
  id: string;
  title: string;
  file: string;
  source: string;
  symbols: string[];
  themes: string[];
  conditions: ChunkConditions;
  always_if_symbol: boolean;
  always_if_theme: boolean;
  priority: 'critical' | 'high' | 'medium' | 'low';
  related_chunks: string[];
  wordCount: number;
}

export interface ChunkIndex {
  generatedAt: string;
  totalChunks: number;
  taxonomy: {
    themes: string[];
    flags: string[];
    actors: string[];
    regimes: string[];
  };
  chunks: ChunkMeta[];
}

export interface ScoredChunk {
  id: string;
  score: number;
  reasons: string[];
}
